### ISSUE TITLE
Support WaterML 2.0

### ISSUE THREAD

**Issue by rsignell-usgs** [geopython/OWSLib#131]
Excerpted from the Ulmo package issue by @jirikadlec2
https://github.com/twdb/ulmo/issues/77,
but would be great if supported by OWSLib:

"It would be nice to support WaterML 2.0 in ulmo. WaterML 2 is a xml format for hydrologic data and it is an official standard of the OGC:
http://www.opengeospatial.org/standards/waterml

I think it's OK if only the getValues() method with an url parameter is supported.

An example WaterML 2.0 request is here:
http://data.fmi.fi/fmi-apikey/1cb8a6f3-d8f4-4ae7-8fc3-0b9449683cfb/wfs?request=getFeature&storedquery_id=fmi::observations::weather::timevaluepair&fmisid=101152&starttime=2013-08-01T00:00:00Z&endtime=2013-08-05T00:00:00Z&timestep=60&parameters=temperature

(this is a time-series of air temperature at a station in Finland)

**Comment by mullenkamp** [comment]
Hi, has @peterataylor 's work been integrated?

**Comment by peterataylor** [comment]
Hi @mullenkamp - yes it got merged in a while back by @kwilcox, see https://github.com/geopython/OWSLib/commit/c73c06eddd059836fcc7f0c2301c9becf8cf1897.

**Comment by mullenkamp** [comment]
Thanks. I was only asking because this issue is still opened, but (as you said) it looked like it got implemented.

**Comment by cehbrecht** [comment]
If I understand correctly this issue is closed by PR #241 since version 0.12.0. I close it now.
