### ISSUE TITLE
Problems with getrecords getrecords2 

### ISSUE THREAD

**Issue by hmedrano** [geopython/OWSLib#192]
Hi, i recently installed GI-CAT broker catalog service (http://essi-lab.eu/do/view/GIcat/WebHome) to harvest some endpoints in our thredds server with ncIso service, I activated the CSW/ISO 2.0.2 interface.

My question is which method should i be using to query records, "getrecords" or "getrecords2" , because its seems that some functionality is available in "getrecords", but still not in "getrecords2", (I have the owslib.**version** : '0.8.7')

For instance:

``` python
keyword1 = fes.PropertyIsLike(propertyname='csw:AnyText', literal='%CNK30%', wildCard='%')
keyword2 = fes.PropertyIsLike(propertyname='csw:AnyText', literal='%PER-T500%', wildCard='%')
serviceType = fes.PropertyIsEqualTo(propertyname='dc:Type', literal='dataset')
filter_list = [fes.And([keyword1,keyword2,serviceType])]
endpoint = 'http://myserver:8080/gi-cat/services/cswiso?'
csw = CatalogueServiceWeb(endpoint,timeout=30)
csw.getrecords2(constraints=filter_list,esn='full',maxrecords=10)
print csw.results
print csw.request
# getService_urls not working with my csw service.
print csw.getService_urls()
# Response is []
```

QUESTION:
The response i get doesn't have nothing in the references tag, thats why the getService_urls() method is not working.  Is it that I'm doing something wrong in my query or my csw interface is lacking of something?

---

But if I use "getrecords" method with the outputschema GMD ("http://www.isotc211.org/2005/gmd"), I can get the URL, but not with any method, but by parsing the xml in the record response.

``` python
endpoint = 'http://myserver:8080/gi-cat/services/cswiso?'
csw = CatalogueServiceWeb(endpoint,timeout=30)
# Keywords are joined by an "OR" operator ONLY !
csw.getrecords(keywords=['PER-T500'],outputschema="http://www.isotc211.org/2005/gmd",typenames='gmd:MD_Metadata',esn='full',qtype='dataset',maxrecords=10)
print csw.results
print csw.request
dapUrls = []

from xml.dom import minidom

# Get the "gmd:URL" TagName nodeValue
for rec in csw.records:
     xmldoc = minidom.parseString(csw.records[rec].xml)
     itemlist = xmldoc.getElementsByTagName('gmd:URL')
     dapUrls.append(itemlist[0].childNodes[0].nodeValue)

# print opendap URL's
print '\n'.join(dapUrls)
# I get the opendap url list.
```

The thing with getrecords is that i can't find a way to join keywords with an "AND" operator. But "getrecords2" can't handle the outputschema GMD, it raises an IndexError exception. 

``` python
endpoint = 'http://myserver:8080/gi-cat/services/cswiso?'
csw = CatalogueServiceWeb(endpoint,timeout=30)
csw.getrecords2(esn='full',outputschema='http://www.isotc211.org/2005/gmd',typenames='gmd:MD_Metadata' , maxrecords=10)
# This raises an IndexError exception
```

QUESTION:
Is there a way to join keywords with an AND operator using the getrecords method ?

Thank you!.
FavioMJ.

**Comment by ocefpaf** [comment]
Can someone post the list link here? I have a the same question and this issue is the very "googleable," and and I cannot find it in the mailing list :-(

**Comment by tomkralidis** [comment]
@ocefpaf looks like this never made it to the mailing list.  Perhaps you can post to the list with your specific question?

**Comment by ocefpaf** [comment]
I avoid mailing list as much as I can :smile: 

But I'll try to do it later today... Thanks.
