### ISSUE TITLE
Test or Example for WFS Get with Filter

### ISSUE THREAD

**Issue by avowkind** [geopython/OWSLib#198]
I've looked through the tests and docs and can't find an example of the creation of a WFS request with a Filter. 

The code implies something  like
filter1 = fes.PropertyIsEqualTo("property", "value")
fr = fes.FilterRequest()
filter_fes = fr.setConstraint(filter1)

get_wfs = wfs.getfeature( 
    typename=[layer],
    filter= filter_fes,
    )

But I can't get this to work so I suspect I'm missing a crucial step. 

PS. I should add that I'm very pleased with the library as a whole. 

Also note that the POST request for WFS is unimplemented.

**Comment by Mounirsky** [comment]
Do you know, how to de a filter with multiple values ?

**Comment by tomkralidis** [comment]
Please post questions to the owslib-users mailing list. OWSLib.  GitHub issues are for software bugs/enhancements and related tasks.
