### ISSUE TITLE
Cannot create a collector using `set_datum` property.

### ISSUE THREAD

**Issue by ocefpaf** [geopython/OWSLib#218]
Hi, I am experiencing an issue when creating a collector like this:

```python
from pyoos.collectors.coops.coops_sos import CoopsSos

collector = CoopsSos()
sos_name = 'water_surface_height_above_reference_datum'

datum = 'NAVD'
collector.set_datum(datum)
collector.end_time = stop
collector.start_time = start
collector.variables = [sos_name]
response = collector.raw(responseFormat="text/csv")
```

With OWSLib version > 0.8.9 I get `got an unexpected keyword 'result'`, but it works nicely with OWSLib <= 0.8.9.  The only change I see that could be the culprit is the passing of the keyword argument to openURL (that is absent in previous versions):

```python
response = openURL(base_url, data, method, username=self.username, password=self.password, **kwargs).read()
```

**Comment by tomkralidis** [comment]
I'm not familiar with pyoos but I'm guessing @kwilcox is. I'm also guessing this is somehow related to https://github.com/geopython/OWSLib/commit/bfff06eb45a5773428aa516752fa6801c94a1f57.

@lukecampbell any idea?

**Comment by ocefpaf** [comment]
Forgot to mentioned that I am using pyoos 0.6.2.

**Comment by lukecampbell** [comment]
Wow, I somehow missed this.
