### ISSUE TITLE
Requests returns fault in WCS 1.1.1

### ISSUE THREAD

**Issue by wsidl** [geopython/OWSLib#245]
When requesting WCS 1.1.1 or 1.1.0, a stack is generated and the cause is on this line:

```
wcs110.py:268
name=elem.find(nmSpc.OWS('ProviderName'))

AttributeError: 'NoneType' object has no attribute 'find'
```

In this case, this call is made in the ServiceProvider class, but this WCS Service does not provide this section, so the element will not exist.

Following adjustment will fix this:

```
wcs110.py:55
self.provider=None if elem is None else ServiceProvider(elem, self.ns)
```

**Comment by tomkralidis** [comment]
Fixed in 55b38f306b545fd5a80309b85415f93bc22a7441
