### ISSUE TITLE
No support for WCS 1.1.2

### ISSUE THREAD

**Issue by wsidl** [geopython/OWSLib#246]
Running WCS service that natively uses 1.1.2 will generate an empty object with no fault or error.

**Comment by cehbrecht** [comment]
See also #430 which adds support for WCS 2.0.

**Comment by olejorgenb** [comment]
A workaround is to ask the server for a specific version.

In my case `https://wms.geonorge.no/skwms1/wcs.hoyde-dom1_32` used version 1.1.2 as default, but passing in 1.0.1 explicitly worked: `wcs.WebCoverageService("https://wms.geonorge.no/skwms1/wcs.hoyde-dom1_32?version=1.0.1")`
