### ISSUE TITLE
Replace CSW params?

### ISSUE THREAD

**Issue by davidread** [geopython/OWSLib#258]
I've got someone adding parameters to their CSW URL and it's causing problems with OWSlib.csw because it doesn't replace the 'request' parameter:
```python
>>> from owslib.csw import CatalogueServiceWeb
>>> csw = CatalogueServiceWeb('https://webapps.kent.gov.uk/geoportal/csw/discovery?Request=GetCapabilities&Service=CSW')
>>> csw.getrecordbyid(['{1370D20C-04D6-4FB8-8E30-BA6B35655F4B}'])
>>> csw.request
'https://webapps.kent.gov.uk/geoportal/csw/discovery?Request=GetCapabilities&Service=CSW&outputFormat=application%2Fxml&service=CSW&outputSchema=http%3A%2F%2Fwww.opengis.net%2Fcat%2Fcsw%2F2.0.2&request=GetRecordById&version=2.0.2&elementsetname=full&id=%7B1370D20C-04D6-4FB8-8E30-BA6B35655F4B%7D'
>>> csw.response
'... <csw:Capabilities ...'
```
i.e. it is still doing a capabilities request rather than GetRecordById, because the 'Reqeust=GetCapabilities' param is hanging around. Would you be against stripping out params that we add, or perhaps I can add that functionality into _invoke() @tomkralidis ?

**Comment by tomkralidis** [comment]
The user needs to provide the base endpoint in order for OWSLib (and any CSW client) to interact with the CSW correctly.  I would see something like this being done upstream of init'ing `owslib.csw.CatalogueServiceWeb`, i.e.:


```pycon
>>> endpoint = 'https://webapps.kent.gov.uk/geoportal/csw/discovery?Request=GetCapabilities&Service=CSW'.split('?')[0]
>>> csw = CatalogueServiceWeb(endpoint)
csw.getrecordbyid(['{1370D20C-04D6-4FB8-8E30-BA6B35655F4B}'])
>>> csw.request
'https://webapps.kent.gov.uk/geoportal/csw?outputFormat=application%2Fxml&service=CSW&outputSchema=http%3A%2F%2Fwww.opengis.net%2Fcat%2Fcsw%2F2.0.2&request=GetRecordById&version=2.0.2&elementsetname=full&id=%7B1370D20C-04D6-4FB8-8E30-BA6B35655F4B%7D'
```

**Comment by davidread** [comment]
Thanks for commenting on this so quickly! The reason I ask is that there is the functionality in wms.py to replace the parameters, and therefore pass through others that may be useful. For example this WMS from Surrey contains layers from several regions in surrey, selected using the 'MapSource' param. You specify it in the URL and the parameter is passed through:
```python
>>> from owslib.wms import WMSCapabilitiesReader
>>> wms_capabilities = WMSCapabilitiesReader()
>>> wms_capabilities.capabilities_url('http://isharemaps.surreyheath.gov.uk/ishare5.0.web/GetOWS.ashx?MapSource=SurreyHeath/Inspire')
'http://isharemaps.surreyheath.gov.uk/ishare5.0.web/GetOWS.ashx?MapSource=SurreyHeath%2FInspire&service=WMS&request=GetCapabilities&version=1.1.1'
```
It is also helpful for passing through user and password parameters. You could argue that this is outside of the OGC spec, but all the same it is in use in the wild and helpful.

So would you mind if we added to csw.py this ability to replace params, along the lines of this: https://github.com/geopython/OWSLib/blob/f6dc647c489eacf9c7e4083f8b0b68e0a44f756f/owslib/wms.py#L607-L612 ?

If not, I could strip off particular params before I call owslib, but this functionality may be useful to others too, and I'd be interested in what you think.

**Comment by tomkralidis** [comment]
@davidread ah, ok.  So basically strip the following from the base URL before starting interaction with the CSW? :

- version
- service
- request
- acceptformats
- acceptversions
- sections

How would this happen in `owslib.csw.CatalogueServiceWeb` on init?  Would this be default behaviour (not preferred)?  Or would this be an argument?

Having other parameters (like, say, `MapSource`, etc.) works as the base URL is meant to be opaque in that manner.  What's the use case where a full CSW URL (and not the base URL) is sent to OWSLib?

**Comment by davidread** [comment]
The use case for extra parameters is that CKAN offers a form for a CSW owner to set up CKAN to harvest from it, and they are asked for their CSW URL. Usually they understand this all and provide the base URL. However the URL with request=GetCapabilities parameter seems to be put in in a number of cases - 3 out of 30 in the experience of data.gov.uk - see http://data.gov.uk/harvest .

I think that is because you can put it in a browser and show that the server is working - much better feedback than a base URL which doesn't do anything or gives an error. I imagine that GIS software will accept CSW URLs with the request param filled, and it will strip them off (although I've not tried any). If so, then why not OWSlib too?

**Comment by tomkralidis** [comment]
@davidread thanks for the info.  With CSW 3.0 on the horizon, the base URL of a CSW will now return the Capabilities document instead of an exception.

 Having said this, I wouldn't oppose a pull request which stripped the above mentioned parameters on `owslib.csw.CataloguServiceWeb` init in a manner that doesn't affect backwards compatibility :smile:

**Comment by davidread** [comment]
I found that the latest OWSlib ignores all params in the URL anyway when doing getrecordbyid since this change: https://github.com/geopython/OWSLib/commit/93980623f71eae5e1d20d3b6a3d29058000f18a9 which makes sense. So I'll close this. Thanks for your help!
