### ISSUE TITLE
Failure on an ArcGIS WMS.

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [geopython/OWSLib#266]
I have no idea if the fact that it's an arcGIS WMS has anything to do with it, but I can't seem to get to:
http://gis.charttools.noaa.gov/arcgis/rest/services/MCS/ENCOnline/MapServer/exts/Maritime%20Chart%20Server/WMSServer

I get an error when I try to initialize:

```
In [4]: wms = WebMapService('http://gis.charttools.noaa.gov/arcgis/rest/services/MCS/ENCOnline/MapServer/exts/Maritime%20Chart%20Server/WMSServer')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-579ddc80eade> in <module>()
----> 1 wms = WebMapService('http://gis.charttools.noaa.gov/arcgis/rest/services/MCS/ENCOnline/MapServer/exts/Maritime%20Chart%20Server/WMSServer')

/Users/chris.barker/miniconda/lib/python2.7/site-packages/owslib/wms.pyc in __init__(self, url, version, xml, username, password, parse_remote_metadata, timeout)
     91 
     92         # build metadata objects
---> 93         self._buildMetadata(parse_remote_metadata)
     94 
     95     def _getcapproperty(self):

/Users/chris.barker/miniconda/lib/python2.7/site-packages/owslib/wms.pyc in _buildMetadata(self, parse_remote_metadata)
    106         #serviceIdentification metadata
    107         serviceelem=self._capabilities.find('Service')
--> 108         self.identification=ServiceIdentification(serviceelem, self.version)
    109 
    110         #serviceProvider metadata

/Users/chris.barker/miniconda/lib/python2.7/site-packages/owslib/wms.pyc in __init__(self, infoset, version)
    276     def __init__(self, infoset, version):
    277         self._root=infoset
--> 278         self.type = testXMLValue(self._root.find('Name'))
    279         self.version = version
    280         self.title = testXMLValue(self._root.find('Title'))

AttributeError: 'NoneType' object has no attribute 'find'
```

I've been told that this service has some issues: namely that you had to capitalize certain WMS parameter names or it would not work. So maybe that's the problem?

I haven't had the chance to get your code and try to dig an and debug it -- maybe you have an idea off the bat?

(NOTE: I'm from NOAA, but not the office that runs this service)

**Comment by drnextgis** [comment]
It looks like this service is accessible only as 1.3.0 WMS and not supported by OWSLib.

**Comment by ChrisBarker-NOAA** [comment]
Interesting: that could explain it -- any plans for WMS 1.3 support?

But in any case, one of my Colleagues is accessing it successfully using ( I think 1.1.1), and when I get:

 http://encdirect.noaa.gov/arcgis/services/encdirect/enc_general/MapServer/WMSServer?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetCapabilities

It shows:
<?xml version="1.0" encoding="UTF-8"?>
<WMT_MS_Capabilities version="1.1.1">
  <Service>
    <Name><![CDATA[WMS]]></Name>
    <Title><![CDATA[encdirect_enc_general]]></Title>
    <Abstract>OGC:WMS</Abstract>
.......

so they THINK they are supporting 1.1.1  .

My first foray into this, so I have no idea what might be up.

-Chris

**Comment by drnextgis** [comment]
See https://github.com/geopython/OWSLib/issues/25

**Comment by tomkralidis** [comment]
Is this really a WMS service?  When I try either of:

http://gis.charttools.noaa.gov/arcgis/rest/services/MCS/ENCOnline/MapServer/exts/Maritime%20Chart%20Server/WMSServer?version=1.3.0&request=GetCapabilities&service=WMS

http://gis.charttools.noaa.gov/arcgis/rest/services/MCS/ENCOnline/MapServer/exts/Maritime%20Chart%20Server/WMSServer?version=1.1.1&request=GetCapabilities&service=WMS

I get nothing resembling a WMS.
