### ISSUE TITLE
owslib.interfaces not used?

### ISSUE THREAD

**Issue by cehbrecht** [geopython/OWSLib#274]
owslib has interface classes like `IService` and `IWebMapService` but it seams they are not used. Are they outdated?

**Comment by tomkralidis** [comment]
@cehbrecht they are.  AFAIK they are suggestions as opposed to concrete implementation.  Having said this, it would be worthwhile to bring these up to date as a means to harmonize the various service interfaces.

**Comment by domlowe** [comment]
@cehbrecht @tomkralidis  yep, they were originally defined by @sgillies to specify a common base API pattern that all service classes should implement.

There is a test here that checked whether different service classes implement the interfaces correctly:
https://github.com/geopython/OWSLib/blob/master/tests/doctests/ows_interfaces.txt
Don't know how current it is now -  it probably needs updating along with the interface definitions.

So you're right that in they aren't used directly (the interface code never actually runs) but they do (or did) serve a useful purpose in defining what the harmonized API (across different types of services) should look like.

**Comment by cehbrecht** [comment]
why shouldn't i define and use these interfaces as abstract classes for the implementations?

I'm currently working on the wps module which has also an `IWebProcessingService` interface ... just want to know how i should use them in OWSLib ...

**Comment by domlowe** [comment]
Refactoring the interfaces into abstract classes would probably be the way to do it now. I don't think python properly supported abstract classes when this code was first written (around python 2.5). 

At the moment they are really just a 'guide/template' showing how to define the API for new modules so you don't really need to do much with them - just implement the same API as the interface and say that you implement the IWebProcessingService interface.
