### ISSUE TITLE
Could we get a 0.9.1 bug fix release?

### ISSUE THREAD

**Issue by rsignell-usgs** [geopython/OWSLib#278]
We are having issues with a workflow here: https://github.com/USGS-CIDA/pyGDP/issues/120 that have already been fixed in master here https://github.com/geopython/OWSLib/commit/6f40078e0624079e266e00181b09e76c7956e733

Could we get a 0.9.1 bugfix release?

**Comment by tomkralidis** [comment]
@rsignell-usgs done.
