### ISSUE TITLE
Could we get an OWSLib 0.9.2 release?

### ISSUE THREAD

**Issue by rsignell-usgs** [geopython/OWSLib#284]
To get workflows with the USGS pyGDP package to work,  we need @ayan-usgs's fix in https://github.com/geopython/OWSLib/pull/281, which occurred after the OWSLib 0.9.1 release (see https://github.com/USGS-CIDA/pyGDP/pull/124#issuecomment-142295291).    

Any chance of getting a OWSLib 0.9.2 bug fix release?

**Comment by tomkralidis** [comment]
Done.

**Comment by rsignell-usgs** [comment]
@tomkralidis, thanks so much!
