### ISSUE TITLE
owslib.wps.printInputOutput AttributeError for Process Outputs

### ISSUE THREAD

**Issue by mlacayoemery** [geopython/OWSLib#286]
I'm using owslib 0.9.2 and calling owslib.wps.printInputOutput with a process from processOutputs, causes an AttributeError: 'Output' object has no attribute 'abstract'

I am making the call to a WPS 1.0.0 service on Geoserver 2.8.0 if that makes a difference. When I add an blank abstract to the process outputs it works fine.

**Comment by tomkralidis** [comment]
@mlacayoemery thanks for the report.  Can you provide a test case (preferably with, in this case, a public WPS endpoint) so we can try to reproduce the issue?

**Comment by mlacayoemery** [comment]
Here is an example of code that would cause this problem.

import owslib.wps
wps = owslib.wps.WebProcessingService('http://cida.usgs.gov/climate/gdp/process/WebProcessingService', verbose=False, skip_caps=True)

process = wps.describeprocess('gov.usgs.cida.gdp.wps.algorithm.FeatureWeightedGridStatisticsAlgorithm')

owslib.wps.printInputOutput(process.processOutputs[0])

**Comment by tomkralidis** [comment]
@mlacayoemery is http://cida.usgs.gov/climate/gdp/process/WebProcessingService a valid WPS? I get redirected to another page.

**Comment by cehbrecht** [comment]
i experienced this problem as well when using external wps services ;) This is because the "abstract" will only be set when it is available in the wps description. But "abstract" seems to be optional ... at least its not always available. 

My current workaround was to handle it in my wps application ... but of course we should provide a solution in owslib/wps itself.

**Comment by mlacayoemery** [comment]
I've updated my example with a vaild WPS.

**Comment by mlacayoemery** [comment]
According to the specifications for WPS 1.0.0 (http://portal.opengeospatial.org/files/?artifact_id=24151) and WPS 2.0 (http://docs.opengeospatial.org/is/14-065/14-065.html) the abstract is an optional field.

**Comment by tomkralidis** [comment]
@mlacayoemery thanks for the report.  FYI this is now fixed in master.  Can you verify?

**Comment by mlacayoemery** [comment]
Yes, I can verify that this is fixed in master. Thank you.
