### ISSUE TITLE
fix 3.2 based unit tests

### ISSUE THREAD

**Issue by tomkralidis** [geopython/OWSLib#291]
@kwilcox @daf @brianmckenna our [Travis-CI](https://travis-ci.org/geopython/OWSLib) tests are constantly failing against 3.2 builds starting from https://travis-ci.org/geopython/OWSLib/builds/81882404:

- https://travis-ci.org/geopython/OWSLib/jobs/89142187
- https://travis-ci.org/geopython/OWSLib/jobs/89142188

Any idea what the issue could be?

**Comment by daf** [comment]
Hi @tomkralidis, it looks like the `coverage` library has an issue with Python 3.2, according to what I'm reading here: menegazzo/travispy#20

Supposedly 3.7.1 runs on Python 3.2 OK - but I'm not sure how or if we want to conditionally install coverage based on Python versions.  Thoughts?  @ocefpaf ?

**Comment by ocefpaf** [comment]
I see the some `u''` uses in some places to declare unicode.  I believe that was re-introduced in Python 3.3.

BTW:  There is an unwritten rule that Python 3 starts at 3.4.  I think is no one will be hurt if you stop testing against 3.2.

**Comment by tomkralidis** [comment]
Should we remove [3.2 and 3.3](https://github.com/geopython/OWSLib/blob/master/.travis.yml#L5-L6) tests?

**Comment by daf** [comment]
I'd say yes.

**Comment by tomkralidis** [comment]
Done.  Let's see how the tests go.

**Comment by ocefpaf** [comment]
Funny thing that I found out because of this issue.  You can:

`conda create -n PY1 python=1`

But you cannot:

```
conda create -n PY32 python=3.2
conda create -n PY31 python=3.1
```

(Python 3.3 is still alive and breathing, but barely.)
