### ISSUE TITLE
Get schema suitable for Fiona library parsed from WFS DescribeFeatureType

### ISSUE THREAD

**Issue by jachym** [geopython/OWSLib#293]
For some applications it might be useful to know the schema (attributes, datatypes, geometry types) of the data, distributed via WFS. DescribeFeatureType request return's back XML Schema file, which can be parsed.

New `get_schema(typename)` method of WebFeatureService could return dictionary type, compatible with Fiona schema http://toblerity.org/fiona/manual.html#format-drivers-crs-bounds-and-schema - for easy parsing.

**Comment by jachym** [comment]
See pull request #294

**Comment by jachym** [comment]
The code between WFS 1.0.0 and WFS 1.1.0&2.0.0 can not be shared easy - any opinion, how to approach? Currently implemented only for WFS 1.0.0

**Comment by tomkralidis** [comment]
Great enhancement for sure!  I would suggest schema parsing is put somewhere more generic like `owslib.util.parse_xml_schema` and then any OWSLib component can simply use as part of their implementation.  Thoughts?

**Comment by jachym** [comment]
Hi Tom,

I've moved the code to separate package, but left it in `owslib.feature` package for now - I think, it's too WFS specific code

I've also integrated it to WFS 1.0.0 as well as 1.1.0 and 2.0.0 (some minor tweakings have to be done) and added tests

https://github.com/jachym/OWSLib/commit/6bf8d9f5752fc0a00423119b08a033ab39f0707e

hope, it looks better now

**Comment by jachym** [comment]
Tom,

I'm about to fix the code, but unfortunately, I'm not able to do so for xml.etree.ElementTree If you agree, I  hacked around the tests for supporting lxml only (see the latest code). Otherwise, I did not found, how to construct namespace map (root.nsmap in lxml) using xml.etree.ElementTree only

**Comment by domlowe** [comment]
Hi Jachym,

In Python 2.5 you used to be able to do it like this:
ET._namespace_map.update({'http://www.opengis.net/om': 'om', 'http://www.opengis.net/swe': 'swe',  'http://www.opengis.net/gml': 'gml'})  

Cheers,
Dom

**Comment by tomkralidis** [comment]
@jachym where are there issues on non lxml usage?

**Comment by kwilcox** [comment]
I'm mobile..excuse my inability to link correctly...

`owslib/etree.py` has code to register namespaces in both `lxml` and stdlib `etree`. You can add any additional namespaces you need in the master list that gets added.

**Comment by jachym** [comment]
Hi,

I'm aware, you can construct custom namespace map object and use it for
parsing, but that is not the issue.

Maybe I understand something wrong, but if you have a look at the Schema
file, e.g.

https://www.sciencebase.gov/catalogMaps/mapping/ows/53398e51e4b0db25ad10d288?SERVICE=WFS&REQUEST=DescribeFeatureType&TYPENAME=footprint

You can see, that

<xsd:element name="footprint" substitutionGroup="gml:AbstractFeature"
type="sb:footprintType"/>

name 'footprint' is defined by 'sb:footprintType' - I need to know, which
namespace is representedy by the 'sb' shortcut

with lxml - you can just check the namespace map - root.nsmap['sb'] -> will
point to the namespace I'm looking for

with xml.etree, there is no such thing :-(

I've rewritten it in a way, it should work for most of the usecases [1] - I
hope, it's fine now - let me know

Jachym


[1]
https://github.com/jachym/OWSLib/blob/jachym_master/owslib/feature/schema.py#L71-L81

pá 11. 12. 2015 v 3:38 odesílatel Tom Kralidis <notifications@github.com>
napsal:
