### ISSUE TITLE
Proposal to change MD_Keywords to its own class

### ISSUE THREAD

**Issue by pmdias** [geopython/OWSLib#301]
This proposal affects directly the iso.py module inside OWSLib. Put in a simple way, I'm proposing to change the type of the keywords member of the `iso.MD_DataIdentification` class. Right now, its type is a standard `dict`, and it would change that to a `class MD_Keywords`.

For some context, I'm referencing [this discussion](http://lists.osgeo.org/pipermail/owslib-devel/2013-March/000184.html) in the mailing list, made some time ago.

The purpose of this change is to bring more consistency to the iso.py module, so that every XSD complex type effectively has its appropriate class. Also, using custom Python class would allow to benefit from inheritance and other OOP concepts. I'm actually thinking about the ability to create specializations like for the INSPIRE [GEMET](http://www.eionet.europa.eu/gemet/inspire_themes) keywords and/or national metadata profiles that are compliant with ISO 19115.
```
                        +-------------+
                        | MD_Keywords |
                        +-------------+
                               ^
                               |
                 +-------------+------------+
                 |                          |
          +---------------+    +-------------------------+
          | GEMETKeywords |    | NationalProfileKeywords |
          +---------------+    +-------------------------+
```
I'm already using this, as we are using OWSLib for a metadata editor at work and built an extension around OWSLib, so some of the code that would be needed for this, we already have it done. I'll probably submit a PR sometime on the next hours/days when I have the time.

For now I'm just querying if this change is welcome, as it will break previous implementations of OWSLib that use the keywords as a `dict`. For this maybe we could think of some sort of legagy strategy? (probably using a mapping class?)

**Comment by tomkralidis** [comment]
@pmdias I think this makes sense as long as backwards compatibility can be preserved. Perhaps we can add a deprecation warning once #302 is implemented and out there for some time.

**Comment by pmdias** [comment]
I agree, and while at it, we can also add the warning for #38, that currently is commented out. Any reason for this?

**Comment by tomkralidis** [comment]
Good question.  This should be turned on.

**Comment by tomkralidis** [comment]
@pmdias what about renaming `identification.mdkeywords` into `identification.keywords2`, add the deprecation warning and then fold into `identification.keywords` over time?
