### ISSUE TITLE
Gain control of the services used in testing

### ISSUE THREAD

**Issue by kwilcox** [geopython/OWSLib#312]
Some of the services used in the tests go up and down periodically (or completely disappear). We need to setup our own set of services that can be reliably tested against.

**Comment by kwilcox** [comment]
Placeholder for a list of required services

- [ ] WMS 1.1.1
- [ ] WMS 1.1.1 (auth)

**Comment by tomkralidis** [comment]
@kwilcox any thoughts on the deployment environment? Perhaps a Docker setup?

**Comment by tomkralidis** [comment]
cc @kalxas

Another option is to deploy an OSGeo live instance here.

**Comment by kalxas** [comment]
an OSGeoLive instance might be too heavy for this purpose, it includes 60+ projects, are all of them needed?
How about an Ubuntu 14.04 base with the OSGeoLive ppa on top to select packages from?

**Comment by micahcochran** [comment]
What about Travis running the services locally on the same test box?  So for instance, Travis could start an local instance of MapServer, configure, and then run the tests based on that.

Just talking about what services are preinstalled on Travis, Precise has mapserver 6.0.1 (pretty old), Trusty has mapserver 6.4.1 (last stable version).  mapserver 7.0.0 was released 2015-07-24.  Mapserver 6.4.1 supports WMS, WFS, and WCS for most of those versions.

**Comment by cehbrecht** [comment]
See also #339.
