### ISSUE TITLE
WMS getmap passes kwargs improperly

### ISSUE THREAD

**Issue by pipes161** [geopython/OWSLib#313]
The `getmap `function of `WebMapService `(line 201) improperly passes `kwargs `to `self.__build_getmap_request` (line 255).

`kwargs `should be passed as `**kwargs`, not `kwargs=kwargs`.

Version: 0.10.3

**Comment by geographika** [comment]
I also ran into this today.

See pull request #316 otherwise extra params are sent to server as 'kwargs': {'MYPARAM': 1},

**Comment by kwilcox** [comment]
Merged: https://github.com/geopython/OWSLib/pull/316
