### ISSUE TITLE
getCoverage doesn't work

### ISSUE THREAD

**Issue by slarosa** [geopython/OWSLib#314]
Testing the getCoverage from WCS module of owslib but the GeoTIFF generated is invalid when loading in QGIS. The code which I am testing:
```python
import os
from owslib.wcs import WebCoverageService

folder = '/Users/larosa/test'

w = WebCoverageService('http://wms.pcn.minambiente.it/cgi-bin/mapserv.exe?map=/ms_ogc/wcs/dtm_20m.map', version='1.0.0')
output = w.getCoverage(identifier='EL.DTM.20M', format='GeoTIFF', bbox=(16.022,38.386,16.096,38.439))

with open(os.path.join(folder,'dem.tif'), 'wb') as f:
    f.write(output.read())
```

Am I missing something?

**Comment by elt11alu** [comment]
I have the same problem. Running Geoserver 2.8.0 and owslib. Did you find a solution?

**Comment by slarosa** [comment]
@elt11alu yes, for me was enough to add the others parameters (```crs```,```width```,```height```,```resx```,```resy```) to the ```getCoverage``` method.

Anyway I am getting a GeoTIFF which is not corresponding to the bbox extension passed. In my case I get the whole national territory (Italy).

Please try with the modification as mentioned above and let us know in case it has worked fine for you.

**Comment by domlowe** [comment]
Hi,

This subset works for me:
output = w.getCoverage(identifier='EL.DTM.20M', format='GeoTIFF', bbox=(10,40,18,45), crs='EPSG:4326', width=400, height=300)

![italysubset](https://cloud.githubusercontent.com/assets/1874325/15523020/5d63d19a-225a-11e6-8140-074a0ed7b7c9.png)

Equivalent to:


http://wms.pcn.minambiente.it/cgi-bin/mapserv.exe?map=/ms_ogc/wcs/dtm_20m.map&service=WCS&request=GetCoverage&version=1.0.0&crs=EPSG:4326&bbox=10,40,18,45&format=GeoTIFF&coverage=EL.DTM.20M&width=400&height=300


Dom

**Comment by slarosa** [comment]
@domlowe I re-tried it and has worked fine for me, thanks.
