### ISSUE TITLE
Using WMC class

### ISSUE THREAD

**Issue by Mounirsky** [geopython/OWSLib#317]
Hi,

Can you please show me some examples of how to use WMC class ? Because I want to generate dynamically  a new context using some wms informations ! is it possible ?

Best regards

**Comment by tomkralidis** [comment]
Please use the [mailing list](https://geopython.github.io/OWSLib/#mailing-lists) for general questions.

**Comment by nmtoken** [comment]
I can see that using the mailing list is the correct form of asking about such functionality, but it is  a pity that nobody answered the question posed there.
