### ISSUE TITLE
Example for WFS GetFeature with Filter

### ISSUE THREAD

**Issue by Mounirsky** [geopython/OWSLib#330]
I'm using the latest version of OWSLib, and I'm trying to apply a filter encoding as follow : 

filter1 = fes.PropertyIsEqualTo('Num_ilot',f1)
filter2 = fes.PropertyIsEqualTo('Num_ilot',f2)
filterList = [filter1,filter2]
fr = fes.FilterRequest()
filter_fes = fr.setConstraintList(filterList, tostring=True)

getFeature = wfs.getfeature(typename = [name], filter=filter_fes, outputFormat="application/json", bbox = bb)

it run but it don't consider the filter !! knowing that the xml content  of filter_fes is right.
Do you have some ideas ?

regards,

**Comment by tomkralidis** [comment]
Please post questions to the OWSLib-users mailing list. OWSLib's GitHub issues are for software bugs/enhancements and related tasks.
