### ISSUE TITLE
get_schema function doesn't accept any authentication parameters

### ISSUE THREAD

**Issue by karakostis** [geopython/OWSLib#345]
The get_schema function (https://goo.gl/tcPi8L) doesn't accept as input authentication parameters: username and password.

On the other hand the openURL function takes as parameters the username and password (https://goo.gl/B4C7zE)

Inside the get_schema we call the openURL function. IMO we should pass username and password as parameters in the get_schema function.

A quick fix would be to modify the get_schema static function so that it accepts as input the authentication parameters:

def get_schema(url, typename, version='1.0.0', timeout=30, username=None, password=None):
    ...

**Comment by drnextgis** [comment]
Seems like this issue may be closed as fixed.

**Comment by cehbrecht** [comment]
Seems to be fixed by PR #385.
