### ISSUE TITLE
SOS username and password missing

### ISSUE THREAD

**Issue by murdav** [geopython/OWSLib#347]
Checking https://github.com/geopython/OWSLib/blob/master/owslib/sos.py#L25 I see that username and password are missing while they are assigned in https://github.com/geopython/OWSLib/blob/master/owslib/swe/observation/sos200.py#L50

D

**Comment by pesekon2** [comment]
Hi @murdav, 

I'm going to work with SOS and before I start I would like to fix some connected issues in OWSLib. 

Please, can you give me some specification of this issue? When should username and password be required, some example of code or something? Because this issue doesn't seem so sophisticated to me, but it should be better to know all possibilities, because in other case it can also result in worse...

**Comment by murdav** [comment]
Hi @pesekon2,

I can certain link WMS username/password implementation:
https://github.com/geopython/OWSLib/blob/master/owslib/wms.py#L50
https://github.com/geopython/OWSLib/blob/master/owslib/map/wms130.py#L59
https://github.com/geopython/OWSLib/blob/master/owslib/map/wms130.py#L385

I simply saw that username and password were missing in the OWSLib SOS implementation. I would say it's an added point to have them when trying to access the getcapabilities if the requested service is using it.

@tomkralidis can give you (and me of course) more information?

D

**Comment by tomkralidis** [comment]
@murdav / @pesekon2 I see username and password are implemented in `owslib.swe.observation.sos100` and `owslib.swe.observation.sos200`, so it looks like `owslib.sos.SensorObservationService` needs updating to handle/pass these accordingly.

**Comment by pesekon2** [comment]
Hi, 

I have created a fork of this repository and update the [owslib.sos.SensorObservationService](https://github.com/pesekon2/OWSLib/blob/master/owslib/sos.py#L22). I will make a pull request tonight after tests. There was just problem that SOS didn't provide username and password to further methods which have it implemented. 

In case you have something more to do with SOS, please let me know and I would like to try to solve it.

**Comment by murdav** [comment]
Great @pesekon2. I would say that was I needed. Thanks again.

**Comment by pesekon2** [comment]
@murdav / @tomkralidis 
I haven't find any issue with my patch. Pull request done [here](https://github.com/geopython/OWSLib/pull/370)
