### ISSUE TITLE
Get update sequence value from wms

### ISSUE THREAD

**Issue by ymoisan** [geopython/OWSLib#355]
It would be nice if we could retrieve the updateSequence attribute from the capabilities document.  One way to do that now is to parse the XML manually as a function of version number.  Here are example xml representations of the capabilities document for : 

WMS 1.1.1

<WMT_MS_Capabilities version="1.1.1" updateSequence="2017-01-09T13:26:25Z">\ ...

WMS 1.3.0

<WMS_Capabilities xmlns="http://www.opengis.net/wms" xmlns:sld="http://www.opengis.net/sld" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ms="http://mapserver.gis.umn.edu/mapserver" version="1.3.0" updateSequence="2017-01-09T13:26:25Z"...

TIA

**Comment by tomkralidis** [comment]
Implemented for all OWSs, accessible via a given service object's `updateSequence` property.
