### ISSUE TITLE
update CSW tests against NOAA NGDC 

### ISSUE THREAD

**Issue by tomkralidis** [geopython/OWSLib#357]
Looks like the CSW (https://www.ngdc.noaa.gov/geoportal/csw) used in https://github.com/geopython/OWSLib/blob/master/tests/doctests/csw_uuid_constrain.txt is now 404/has been moved.

cc'ing @rsignell-usgs or @kwilcox for possible help to update this test.

**Comment by Yuanjie0913** [comment]
Please try this URL with the same search criteria https://www.nodc.noaa.gov/archivesearch/csw.
Please let me know if it works. 

Li
