### ISSUE TITLE
CSW ExceptionReport locator=request parameter value not valid

### ISSUE THREAD

**Issue by murdav** [geopython/OWSLib#360]
Hello,

Using 0.14 and Python 3.5 I got this error message for this code:

```
from owslib.csw import CatalogueServiceWeb
csw = CatalogueServiceWeb('http://www.geoportale.isprambiente.it/geoportale/csw?request=GetCapabilities&service=CSW')
```
or also
```
from owslib.csw import CatalogueServiceWeb
csw = CatalogueServiceWeb('http://www.pcn.minambiente.it/geoportal/csw?request=getCapabilities&service=csw')

```
`ExceptionReport: 'Parameter value not valid: locator=request'`
(original is ExceptionReport: 'Valore del parametro non valido: locator=request')

Why?

Thanks,

D

**Comment by tomkralidis** [comment]
FYI this works for me in Python 2.x and 3.x:

```python
from owslib.csw import CatalogueServiceWeb
csw = CatalogueServiceWeb('http://www.geoportale.isprambiente.it/geoportale/csw')
```

In the future, please address questions to the OWSLib-users list.
