### ISSUE TITLE
High level functions to help construct and parse CSW queries

### ISSUE THREAD

**Issue by rsignell-usgs** [geopython/OWSLib#365]
It's amazing how powerful the CSW query functionality is, but it involves a lot of OWSlib code to invoke it (see this [example notebook](https://gist.github.com/anonymous/12f97e59c9b1aaa2969a3437df1b2831)).    

We were thinking it would be nice to have a function that had a lot of optional parameters that would just return a list of endpoints as URLs, like 
```
endpoint_list = get_service_endpoints(csw_endpoint_list, bbox=None, time_extent=None, anyText=None, serviceType=None)
```

which would support our typical use pattern: that we are querying a CSW endpoint (or list of endpoints) looking for services of a specific type (e.g. WMS), with certain conditions:
* within a specified bounding box
* within a specified time extent
* containing certain words (apiso:AnyText)
* not containing certain words
* containing specified serviceType (e.g. WMS)

And what the user wants back is just a list of service endpoints (e.g. WMS service endpoints). 

The `anyText` parameter could take a list that uses the [fancy syntax of @kwilcox](https://github.com/geopython/OWSLib/pull/60):
```
[a,b,c]
a || b || c

[[a,b,c]]
a && b && c

[[a,b],[c],[d],[e]] or [[a,b],c,d,e]
(a && b) || c || d || e
```

Good idea?

**Comment by tomkralidis** [comment]
+1

**Comment by rsignell-usgs** [comment]
@ocefpaf, what do you think?

**Comment by ocefpaf** [comment]
definitely :+1:
