### ISSUE TITLE
support LegendURL +format for WMTS 1.0.0

### ISSUE THREAD

**Issue by murdav** [geopython/OWSLib#366]
Dear All,

Reading http://portal.opengeospatial.org/files/?artifact_id=35326, page 20-21 I saw there is the possibility to have within the Style element:
- Title 
- Identifier
- isDefault
- LegendURL (currently missing)
- Abstract (currently missing)
- Keywords (currently missing)

A getcapabilities example could be:
http://wmts.geo.admin.ch/1.0.0/WMTSCapabilities.xml

```
***
*
<Style>
<ows:Title>Karst catchment units</ows:Title>
<ows:Identifier>ch.bafu.karst-einzugsgebietseinheiten</ows:Identifier>
<LegendURL format="image/png" xlink:href="http://api3.geo.admin.ch/static/images/legends/ch.bafu.karst-einzugsgebietseinheiten_en.png"/>
</Style>
<Format>image/png</Format>
```

Is there any program to add it?
Interested line/s should be around: https://github.com/geopython/OWSLib/blob/master/owslib/wmts.py#L736

If not I can do a pull request.

Thanks,

D

**Comment by tomkralidis** [comment]
hi @murdav thanks for the report.  Pull requests (with relevant tests) would be welcome.

**Comment by murdav** [comment]
Linked to https://github.com/geopython/OWSLib/pull/367.
