### ISSUE TITLE
CSW getrecords2 and getrecordbyid results are different for the same ID

### ISSUE THREAD

**Issue by murdav** [geopython/OWSLib#369]
Dear All,

I was checking some CSWs, but I found a mismatch while:

```
from owslib.csw import CatalogueServiceWeb
from owslib.fes import PropertyIsEqualTo, PropertyIsLike, BBox
csw = CatalogueServiceWeb('http://geoservices.retecivica.bz.it/geonetwork/srv/ita/csw?', version='2.0.2')
csw_query = PropertyIsEqualTo('csw:AnyText', 'bozen')

csw.getrecords2(constraints=[csw_query])
```

Now comparing the result values for:

`csw.records['p_bz:913df91e-1330-4b20-add3-f80e696e0378']` the `publisher `field is `None`

while executing (same ID)

`csw.getrecordbyid(id=['p_bz:913df91e-1330-4b20-add3-f80e696e0378'])`

I got:

```
csw.records['p_bz:913df91e-1330-4b20-add3-f80e696e0378'].publisher
Out[12]: 'Provincia Autonoma di Bolzano (IPa: p_bz) - Ripartizione 28 - Natura, paesaggio e sviluppo del territorio - Cartografia provinciale e coordinamento geodati'
```

You will also notice that several attributes have different values, but for example the `subjects `field is correct on both.

Could you double check?

D

**Comment by kwilcox** [comment]
Could you try with `esn='full'` as a parameter to the `getrecords2` method? They(`getrecords2`/`getrecordbyid`) have different defaults for `esn`. I'd like to elimitate that before digging in further.

**Comment by murdav** [comment]
@kwilcox it works as you were suggesting using `esn='full'` (instead of the default 'summary') I absolutely didn't think about something similar. Thanks!
