### ISSUE TITLE
Feature: WPS Request with Bounding Box

### ISSUE THREAD

**Issue by tgmendes** [geopython/OWSLib#379]
Hello,

We are using OWSLib to make WPS requests, and we found out that there is no clear support to send requests with a defined bounding box (only the ability to parse them). Is this true?

If so, is there a workaround or is there a plan to include this feature?

Regards,
Tiago

**Comment by cehbrecht** [comment]
this is also on my wish list to make the bbox work. I did already some work on my fork:
https://github.com/bird-house/OWSLib/blob/pingudev/owslib/wps.py#L1449

But it is not finished ... i can just remember that it didn't work yet with pywps-4.

**Comment by tgmendes** [comment]
Thank you very much!

Your implementation worked for us, we just had to make some minor modifications to adapt to our needs.

Cheers!

**Comment by cehbrecht** [comment]
Thanks for testing :) 

My patched owslib fork is also available on a conda channel:
https://anaconda.org/birdhouse/owslib/files

But i will check this bbox code and try to get it into the official owslib.

**Comment by cehbrecht** [comment]
@tgmendes 
... forgot to ask: do you have your modifications on a github fork? Which WPS service are you using?

**Comment by tgmendes** [comment]
We did not place any modifications on a github fork because we only created a wrapper so that the BBOX parameters were passed as individual parameters instead of a string or list. If you find this interesting I can send you the file or place it in a fork.

Regarding WPS, we are using a private WPS service, which is maintained by Terradue.

**Comment by cehbrecht** [comment]
@tgmendes 
if you don't mind you could add a gist to this ticket (https://gist.github.com/). Thanks.

**Comment by tgmendes** [comment]
Here you go:
https://gist.github.com/tgmendes/58d0767ca1a5950c2f91d661912202ac

**Comment by cehbrecht** [comment]
This is fixed with PR #384.
