### ISSUE TITLE
ows namespace gets lost in a GetRecords request if only referred to in an OGC Filter property name

### ISSUE THREAD

**Issue by andrew-wils** [geopython/OWSLib#391]
csw.py calls cleanup_namespaces, which removes all namespaces of which no elements are included.
However, a GetRecords request with a spatial filter will typically include an OGC Filter property name "ows:BoundingBox". 
Because there is no ows element in the request, the namespace is removed, and the property name becomes unusable.

The source file partially acknowledges this problem by re-inserting namespaces from the typeNames attribute. However, this is not enough.

**Comment by tomkralidis** [comment]
Fixed in master.
