### ISSUE TITLE
WCS 1.1.1 returns no coverages on ESRI WCS endpoint

### ISSUE THREAD

**Issue by rsignell-usgs** [geopython/OWSLib#401]
The USACE has a lidar database available via ESRI WCS that I'm trying to access.   I can access via WCS version 1.0.0, list contents, and do `getCoverage` requests on identifiers listed in the contents, but with version 1.1.1 (also supported by the ESRI WCS server) there are no layers listed in the contents:
```python
from owslib.wcs import WebCoverageService
endpoint='https://usace-ags.esriemcs.com/arcgis/services/JALBTCX/JALBTCX_Products_1mGrid/ImageServer/WCSServer?request=GetCapabilities&service=WCS'
wcs = WebCoverageService(endpoint,version='1.1.1',timeout=60)
len(wcs.contents)
```
returns
```
0
```

**Comment by cefect** [comment]
Having the same issue in Canada

`url='https://datacube.services.geo.ca/ows/elevation'`

But this server doesn't seem to support any other WCS versions :(
