### ISSUE TITLE
How to read time-specific data from ESRI WCS endpoint?

### ISSUE THREAD

**Issue by rsignell-usgs** [geopython/OWSLib#402]
The USACE has a lidar database available via ESRI WCS that I'm trying to access.   I can access via WCS version 1.0.0, but I'm struggling to figure out how to read the data within a specific time range?

There are two sets of lidar data associated with this coverage, one survey in 2015 and one in 2017.

I can see the time range from `describeCoverage`:
https://usace-ags.esriemcs.com/arcgis/services/JALBTCX/JALBTCX_Products_1mGrid/ImageServer/WCSServer?request=DescribeCoverage&service=WCS&version=1.0.0&identifiers=JALBTCX_Products_1mGrid
listed as:

```
<temporalDomain>
<timePeriod>
<beginPosition>2015-06</beginPosition>
<endPosition>2017-10</endPosition>
<timeResolution>P2M</timeResolution>
</timePeriod>
</temporalDomain>
```
but when I try to specify `time='2015-06-01'`:
```
from owslib.wcs import WebCoverageService
endpoint='https://usace-ags.esriemcs.com/arcgis/services/JALBTCX/JALBTCX_Products_1mGrid/ImageServer/WCSServer?request=GetCapabilities&service=WCS'
wcs = WebCoverageService(endpoint,version='1.0.0',timeout=60)
identifier='JALBTCX_Products_1mGrid'
bbox = (-81.7638195, 25.9175701,-81.7051113, 25.9691658)  # Marco Island
output = wcs.getCoverage(identifier=identifier,bbox=bbox,crs='EPSG:4326',format='GeoTIFF',
                         resx=0.0001, resy=0.0001, time='2015-06-01')
```
I get  back:
```
---------------------------------------------------------------------------
ServiceException                          Traceback (most recent call last)
<ipython-input-71-931b7f816d27> in <module>()
      1 output = wcs.getCoverage(identifier=identifier,bbox=bbox,crs='EPSG:4326',format='GeoTIFF',
----> 2                          resx=0.0001, resy=0.0001, time='2015-06-01')

~\AppData\Local\Continuum\Miniconda3\envs\IOOS3b\lib\site-packages\owslib\coverage\wcs100.py in getCoverage(self, identifier, bbox, time, format, crs, width, height, resx, resy, resz, parameter, method, **kwargs)
    163 
    164 
--> 165         u=openURL(base_url, data, method, self.cookies)
    166 
    167         return u

~\AppData\Local\Continuum\Miniconda3\envs\IOOS3b\lib\site-packages\owslib\util.py in openURL(url_base, data, method, cookies, username, password, timeout, headers)
    203             if serviceException is not None:
    204                 # and we need to deal with some message nesting
--> 205                 raise ServiceException('\n'.join([str(t).strip() for t in serviceException.itertext() if str(t).strip()]))
    206 
    207     return ResponseWrapper(req)

ServiceException: parameter Time is invalid
```
I get this same response for these time formats:
`time=['2015-06']`
`time='2015-06'`
`time=['2015-06-01']`
`time='2015-06-01']`

Is this user error or a bug?

**Comment by tomkralidis** [comment]
This looks like an error from the server.

**Comment by rsignell-usgs** [comment]
How did you diagnose that?

**Comment by rsignell-usgs** [comment]
These time-enabled requests to the ESRI WCS Service work, delivering back the 2015 and 2017 data as geotiff

Would I be able to construct these using OWSlib?


2017 LIDAR Data:
https://usace-ags.esriemcs.com/arcgis/services/JALBTCX/JALBTCX_Products_1mGrid/ImageServer/WCSServer?SERVICE=WCS&VERSION=1.0.0&REQUEST=GetCoverage&COVERAGE=JALBTCX_Products_1mGrid&FORMAT=GeoTIFF&BBOX=-81.7638195,25.9175701,-81.7051113,%2025.9691658&WIDTH=720&HEIGHT=720&CRS=EPSG:4326&INTERPOLATION=nearest%20neighbor&TIME=2017-08/2017-12

2015 LIDAR Data:
https://usace-ags.esriemcs.com/arcgis/services/JALBTCX/JALBTCX_Products_1mGrid/ImageServer/WCSServer?SERVICE=WCS&VERSION=1.0.0&REQUEST=GetCoverage&COVERAGE=JALBTCX_Products_1mGrid&FORMAT=GeoTIFF&BBOX=-81.7638195,25.9175701,-81.7051113, 25.9691658&WIDTH=720&HEIGHT=278&CRS=EPSG:4326&INTERPOLATION=nearest%20neighbor&TIME=2015-06/2015-08

**Comment by rsignell-usgs** [comment]
Okay, @tomkralidis helped me figure out that for this endpoint, there needs to be two values in a list, and the values have to be within the time extents.   This works:

```
from owslib.wcs import WebCoverageService
endpoint='https://usace-ags.esriemcs.com/arcgis/services/JALBTCX/JALBTCX_Products_1mGrid/ImageServer/WCSServer?request=GetCapabilities&service=WCS'
wcs = WebCoverageService(endpoint,version='1.0.0',timeout=60)
identifier='JALBTCX_Products_1mGrid'
bbox = (-81.7638195, 25.9175701,-81.7051113, 25.9691658)  # Marco Island
output = wcs.getCoverage(identifier=identifier,bbox=bbox,crs='EPSG:4326',format='GeoTIFF',
                         resx=0.0001, resy=0.0001, time=['2015-06-06', '2015-06-08'])
