### ISSUE TITLE
line 569 in util.py with python 3.6.2 fails

### ISSUE THREAD

**Issue by paalped** [geopython/OWSLib#408]
I had to modify line 569 in util.py to:                
    return raw_text.replace(bom, ''.encode('utf-8'))
for this lib to work in 3.6.2

**Comment by cehbrecht** [comment]
This is function `util.strip_bom`:
https://github.com/geopython/OWSLib/blob/54b7b585324afc91532eb4900ccf0ef064c5bbf2/owslib/util.py#L578

Add a unit test first.

**Comment by cehbrecht** [comment]
@paalped It took me a bit more to fix this for Python 2/3. Please check if it works you.

See: 
https://github.com/geopython/OWSLib/blob/56410931e3234e46a077fb15c436294154c30a0c/owslib/util.py#L578

And the test:
https://github.com/geopython/OWSLib/blob/56410931e3234e46a077fb15c436294154c30a0c/tests/test_util.py#L7
