### ISSUE TITLE
Is there a programmatic way to work with CSW nextrecord?

### ISSUE THREAD

**Issue by axfelix** [geopython/OWSLib#417]
Hi,

I can't see anything in the documentation for a function to automatically populate csw.records with the next set, so I'm wondering if we're just intended to query again with `csw.getrecords2(startposition=csw.results['nextrecord'])`.

Thanks!

**Comment by tomkralidis** [comment]
Given `startposition` and `maxrecords` you should be able to cycle through the records.  Simple example at https://gist.github.com/tomkralidis/47a8bce9ca8338b66719

**Comment by cehbrecht** [comment]
I would see this question as answered.
