### ISSUE TITLE
Implement OGC OWS Context format

### ISSUE THREAD

**Issue by allixender** [geopython/OWSLib#441]
There is growing interest to use the OGC Web Services Context Document (OWS Context) format: http://www.opengeospatial.org/standards/owc

OWS Context has a conceptual model, an Atom XML encoding and a GeoJSON encoding:

- OGC OWS Context Conceptual Model 1.0 (12-080r2)
- OGC OWS Context Atom Encoding Standard 1.0 (12-084r2)
- OGC OWS Context GeoJSON Encoding Standard 1.0 (14-055r2)

Official Schemas (Atom XML): http://schemas.opengis.net/owc/

OWS Context including developer resources and information on in-progress work is curated on a public site for additional resources: http://www.owscontext.org/

Additional info for OWC GeoJSON:
There were some ambiguities with the definitions of OWC Geojson Encoding which so far haven't really been brought forward to the OGC working group for OWC (https://allixender.blogspot.co.at/2017/07/ogc-ows-geojson.html and ZGIS/smart-owc-geojson#4). It would be nice to get some feedback in order to have a good implementation in Geopython/OWSlib.

**Comment by tomLandry** [comment]
Just checking if discussion from https://github.com/geopython/pywps/issues/322 should be ported here.
