### ISSUE TITLE
rename async option in wps.execute

### ISSUE THREAD

**Issue by cehbrecht** [geopython/OWSLib#455]
I just introduced the `async` option in `wps.execute` in #444. After updating my editor with the latest `pycodestyle` I get the warning that `async` will be a reserved keyword starting with Python 3.7:

```
W606 'async' and 'await' are reserved keywords starting with Python 3.7
```

So, better we choose a different parameter name for `async` before people start using it with OWSLib release 0.17.

Suggestions?

* [WPS 2.0.0](http://docs.opengeospatial.org/is/14-065/14-065.html#59) introduces `mode` with allowed values String{sync | async | auto}.
* inverse value `sync` instead of `async`... well, don't like this.
* ???

**Comment by lazaa32** [comment]
`mode` seems like good option to me. Alternatively, one of the parameters `storeExecuteResponse` or `status` can be used but I'm not really sure if it wouldn't be more confusing. I'd prefer `mode`.

**Comment by cehbrecht** [comment]
`storeExecuteResponse` and `status` parameters would be the exact fit for WPS 1.0.0 ... but I always found it confusing. Choosing `mode` from WPS 2.0.0 is currently also my preferred option.

If no other opinions come up I will change this before the OWSLib 0.17 release.
