### ISSUE TITLE
Feature request: Custom __str__ method for WPS Process class

### ISSUE THREAD

**Issue by huard** [geopython/OWSLib#459]
So that print(process) displays the identifier.

**Comment by cehbrecht** [comment]
@huard One could also have the identifier+title for print(myprocess) and identifier only for repr(myprocess).

**Comment by huard** [comment]
Tried it, very nice, but I think it breaks the convention for `__repr__`: 

`object.__repr__(self)`
Called by the repr() built-in function to compute the “official” string representation of an object. If at all possible, this should look like a valid Python expression that could be used to recreate an object with the same value (given an appropriate environment). If this is not possible, a string of the form <...some useful description...> should be returned. The return value must be a string object. If a class defines `__repr__()` but not `__str__()`, then `__repr__()` is also used when an “informal” string representation of instances of that class is required.
This is typically used for debugging, so it is important that the representation is information-rich and unambiguous.

So I suppose the `__repr__` could look something like `<owslib.wps.Process identifier object at ...>`.
We have more freedom for `__str__`, but I think it's worth including the fact that it's a wps process, ie something like: `identifier wps.Process: title`

**Comment by cehbrecht** [comment]
@huard I have made an update to the `repr` method. What do you think? How to handle the undefined values? If you like to add a patch for this you are welcome :)

**Comment by huard** [comment]
Looks good. There is nothing left to patch.

**Comment by cehbrecht** [comment]
Ok, thanks.
