### ISSUE TITLE
tests for wcs 2.0.x failing due to metadata changes

### ISSUE THREAD

**Issue by doclements** [geopython/OWSLib#460]
The tests are not passing due to metadata changes at the service used in the testing.

**Comment by cehbrecht** [comment]
@doclements I have seen you have updated the service so that the doctest was working again. Nonetheless I removed the doctest ... it is redundant because we already have a "normal" test in `tests/test_wcs_200.py`  ... so we can maintain just one test.

Please complain if you don't like this :)
