### ISSUE TITLE
Handling Python 2.7 and Python 3.x compatibility

### ISSUE THREAD

**Issue by cehbrecht** [geopython/OWSLib#478]
It looks like [six](https://pythonhosted.org/six/) is the tool of choice to handle Python 2/3 compatibility.  But we haven't used it consistently in the code yet where it would be possible. Example:
https://github.com/geopython/OWSLib/blob/5bd7d1491d963458c45d0608d24977c5c7b2d05a/owslib/swe/observation/sos200.py#L6

How do we handle cases where `six` has no solution yet? Other Projects like `pywps` have a `_compat.py` module to collect those cases centrally.

This gets even more tricky when dealing with string encodings ... I open a new ticket for this.

I just open this ticket to collect common practice and opinions :)

**Comment by QuLogic** [comment]
What cases are missing from `six`?

**Comment by cehbrecht** [comment]
@QuLogic I can't say yet what cases are missing in `six` ... we will figure out when we clean up the code :)

**Comment by cehbrecht** [comment]
Python 2.7 was dropped with release 0.19.
