### ISSUE TITLE
WFS gml features to geoJSON--How?

### ISSUE THREAD

**Issue by smrgeoinfo** [geopython/OWSLib#487]
I'm trying to connect to a WFS, get features, and iterate through the features in the resulting featureCollection, converting the GML to GeoJSON.  I've been trying with owslib and can get the xml as a StringIO object with wfs.getFeature, but can't figure out  how to extract features as ogr.Features that I can use ExportToJSON on. 
Likewise I can't get an ogr.Open to generate a reader I can use ogr.layer.getFeature on for the iteration.  

Can anyone point me at some code that does something like this?
thanks!

**Comment by Cap-JaTu** [comment]
This issue has been open for couple years. Still, the problem persists.

I'm trying to do exactly this same. Need to import WFS polygons and process them with GeoPandas, but it doesn't seen to be possible.
Another approach with osgeo also fails, a request to load a layer and get a feature simply crashes without any explanation.
