### ISSUE TITLE
FutureWarning in util.py?

### ISSUE THREAD

**Issue by rsignell-usgs** [geopython/OWSLib#490]
from the latest version of OWSLib 0.16.0 on conda-forge, I'm getting:
```
C:\Users\rsignell\miniconda3\envs\scipy-2018\lib\site-packages\owslib\util.py:541: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
```
Looks like this has been fixed, perhaps?   
 If so, could we release a new version?

**Comment by cehbrecht** [comment]
I like to have a new release ... but still there are some open issues:
https://github.com/geopython/OWSLib/milestone/2

They might not be critical so we can fix them in the next release. I'm currently using the wps module and feel responsible for it. I hope others take more care about the other modules :)

I would leave the last word to @tomkralidis when to create a release.

Currently I help myself by using my own conda package with the latest code from master:
https://anaconda.org/birdhouse/owslib

@rsignell-usgs you may try it if it already works for you.

**Comment by tomkralidis** [comment]
Suggest we target a release for end August, which will give us a chance to address issues in https://github.com/geopython/OWSLib/milestone/2.  Does this work?

**Comment by cehbrecht** [comment]
works for me :)

**Comment by cehbrecht** [comment]
I thinks this is done.
