### ISSUE TITLE
Is calling __init__ from __new__ in  OWSLib/owslib/feature/wfs110.py necessary?

### ISSUE THREAD

**Issue by vjf** [geopython/OWSLib#520]
I have been trying to 'pickle' instances of "WebFeatureService_1_1_0", but this is difficult because the code calls \_\_init\_\_ from within \_\_new\_\_.

When unpickling the object, 'pickle' calls \_\_new\_\_ to create the instance

(From https://docs.python.org/3/library/pickle.html#pickling-class-instances)

_def load(cls, attributes):
    obj = cls.\_\_new\_\_(cls)
    obj.\_\_dict\_\_.update(attributes)
    return obj_
    
then because this calls \_\_init\_\_, it tries to fully re-create the object, which makes the use of pickle pointless!    
    
In the end, I had to override WebFeatureService_1_1_0.\_\_new\_\_ with one that does not call \_\_init\_\_ to get pickle to work.

Also I understand that python calls \_\_new\_\_ then calls \_\_init\_\_ when creating objects, (https://docs.python.org/3/reference/datamodel.html#object.__new__)

This means that \_\_init\_\_ is called twice!

Is this a bug, or is there a good reason for calling \_\_init\_\_ from within \_\_new\_\_? 

If it is a bug, I'd be happy to submit a pull request for this and the other WFS versions.

**Comment by geographika** [comment]
Resolved with #548

**Comment by geographika** [comment]
@vjf - do you have an example of pickling the WFS class? I get errors as lxml classes can't be pickled:

```python
import pickle
from owslib.wfs import WebFeatureService

wfs_url = "https://demo.mapserver.org/cgi-bin/wfs?"
wfs = WebFeatureService(url=wfs_url, version="2.0.0")

with open("wfs_object.pkl", "wb") as f:
    pickle.dump(wfs, f)
    # TypeError: cannot pickle 'lxml.etree._Element' object
```

Just wondering what approach you used (the `dill` library also fails).

**Comment by vjf** [comment]
@geographika 

It was a long time ago, I think I was using 'diskcache'

This will fail with a TypeError when calling 'pickle.load()' if OWSLib < v0.32.1:

```
from owslib.wfs import WebFeatureService
from diskcache import Cache
import copyreg
from lxml import etree

wfs_url = "https://demo.mapserver.org/cgi-bin/wfs?"
wfs_dk = WebFeatureService(url=wfs_url, version="2.0.0")


def element_unpickler(data):
    return etree.fromstring(data)

def element_pickler(element):
    data = etree.tostring(element)
    return element_unpickler, (data,)

copyreg.pickle(etree._Element, element_pickler, element_unpickler)

def elementtree_unpickler(data):
    data = StringIO(data)
    return etree.parse(data)

def elementtree_pickler(tree):
    data = StringIO()
    tree.write(data)
    return elementtree_unpickler, (data.getvalue(),)

copyreg.pickle(etree._ElementTree, elementtree_pickler, elementtree_unpickler)


cache = Cache()
key = cache.push(wfs_dk)
print(cache.pop(key))
```
