### ISSUE TITLE
"service_ok" check in tests does not recognize unavailable service

### ISSUE THREAD

**Issue by cehbrecht** [geopython/OWSLib#552]
We are using `service_ok` in tests but it fails if the service answers with a "not available" HTML response. See:
https://github.com/geopython/OWSLib/blob/1e5488318358bc189d884dab4fd06d3229f6cd61/tests/test_csw_ngdc.py#L12

... using this service:
http://www.ngdc.noaa.gov/geoportal/csw

**Comment by tomkralidis** [comment]
+1

**Comment by cehbrecht** [comment]
fixed by PR #554.
