### ISSUE TITLE
Support of ISO19115-3:2016 Geospatial Standard

### ISSUE THREAD

**Issue by anotheredward** [geopython/OWSLib#560]
We use an application that uses this library, and have been pointed to this library as where we'd need to add support for the ISO19115-3:2016 Geospatial Standard so it can be supported upstream.
https://github.com/ckan/ckanext-spatial/issues/212

Is this assumption correct?

And do you have an idea of what work would be required or how you might approach adding this support @tomkralidis ?

Thanks :)

**Comment by kalxas** [comment]
Does anyone have access to the ISO specification?
We should start at that point :)

**Comment by anotheredward** [comment]
@kalxas Thanks, I'll get to work on getting us a copy of the ISO specification.

**Comment by camfindlay** [comment]
@anotheredward maybe have a look thorough here to see if there is an openly available spec http://schemas.opengis.net/

**Comment by tomkralidis** [comment]
Echo @kalxas on starting with the spec. A minimal implementation can act as a baseline to start followed by implementing known profiles or implementation. Are there examples of the new ISO out there you can point us to?

**Comment by bonnland** [comment]
Here is a github repo with some examples: 

https://github.com/NCAR/dset-web-accessible-folder-iso19115-3-dev

We currently apply XSLT transforms to these records before harvesting in CKAN.   But we are interested in eventually moving to the new ISO standard because of better support for certain important metadata features.

**Comment by vjf** [comment]
See https://github.com/geopython/OWSLib/pull/900

**Comment by kalxas** [comment]
This has been completed by #900
