### ISSUE TITLE
Q: is lxml required for OWSLib? - nsmap  presence required

### ISSUE THREAD

**Issue by justb4** [geopython/OWSLib#566]
Found intriguing issue in GeoHealthCheck:
https://github.com/geopython/GeoHealthCheck/issues/243
 from a WFS parsed via OWSLib (any version from 0.14.0): the `_capabilities.nsmap` was only available when `lxml` was installed/present. Without `lxml` found no way to get the complete NS mapping (NS URI to prefix map).

So the question is: is `lxml` required for OWSLib? It is not on the `requirements.txt` and I see some optionalities in tests (with/without `lxml`). If not is there some other way to get the NS-Prefix map?

**Comment by cehbrecht** [comment]
@tomkralidis should we make `lxml` a requirement ... and skip the special handling when `lxml` is not available?

**Comment by tomkralidis** [comment]
Given lxml is a heavy requirement OWSLib has workarounds to detect how to parse XML (standard library, lxml, etc.).  Recommendation is for downstream applications using lxml specifics to require lxml per se, if needed.  OWSLib should preserve the capability to not require lxml for installs that do not have the underlying lxml requirements.

**Comment by justb4** [comment]
@tomkralidis yes, I see, with several projects we implemented "escape routes/import sniffing" for `lxml`. But the original issue here is that there is no "NS-Prefix map". NSs are often necessary for WFS requests like GetFeature. So if lxml not avail, how to still obtain the NS-URL-map?

**Comment by tomkralidis** [comment]
As a workaround in this case I would suggest the downstream app pulls this out on their own with something like: https://stackoverflow.com/a/37409050
