### ISSUE TITLE
Enable providing and forwarding HTTP headers for endpoints

### ISSUE THREAD

**Issue by justb4** [geopython/OWSLib#587]
Some OWS endpoint classes allow HTTP Headers via a `headers` dict structure to be passed on creation. For example [WebMapService](https://github.com/geopython/OWSLib/blob/master/owslib/wms.py#L23). But in this case these `headers` are only passed/forwarded when creating a WMS 1.3.0 instance.

For other OWS types like WFS, WMTS and TMS (and probably more) no `headers` can be passed. 

This is needed in cases where a client needs to pass specific  HTTP Header name/values, for example for Authentication via Bearer Token.

**Comment by justb4** [comment]
I can work on this PR upcoming.

**Comment by cehbrecht** [comment]
fixed by PR #613.
