### ISSUE TITLE
WCS access "service error"

### ISSUE THREAD

**Issue by markjessell** [geopython/OWSLib#590]
Hi

I am trying to access a WCS service (that works via QGIS) any thoughts?

thansk in advance

Mark

from owslib.csw import CatalogueServiceWeb
url="http://gaservices.ga.gov.au/site_9/services/DEM_SRTM_1Second_over_Bathymetry_Topography/MapServer/WCSServer"
csw = CatalogueServiceWeb(url)

gives me:
---------------------------------------------------------------------------
ServiceException                          Traceback (most recent call last)
<ipython-input-8-db1e45e6a0f0> in <module>
      3 #url="http://geodiscover.cgdi.ca/wes/serviceManagerCSW/csw"
      4 #url="http://gaservices.ga.gov.au/site_3/services/Bathymetry_Topography/MapServer/WCSServer?request=GetCapabilities&service=WCS"
----> 5 csw = CatalogueServiceWeb(url)
      6 csw.identification.type
      7 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\owslib\csw.py in __init__(self, url, lang, version, timeout, skip_caps, username, password, auth)
     88             self.request = urlencode(data)
     89 
---> 90             self._invoke()
     91 
     92             if self.exceptionreport is None:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\owslib\csw.py in _invoke(self)
    662             self.request = '%s%s' % (bind_url(request_url), self.request)
    663             self.response = openURL(
--> 664                 self.request, None, 'Get', timeout=self.timeout, auth=self.auth
    665             ).read()
    666         else:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\owslib\util.py in openURL(url_base, data, method, cookies, username, password, timeout, headers, verify, cert, auth)
    222             if serviceException is not None:
    223                 # and we need to deal with some message nesting
--> 224                 raise ServiceException('\n'.join([encode_string(t).strip() for t in serviceException.itertext() if encode_string(t).strip()]))
    225 
    226     return ResponseWrapper(req)

ServiceException:

**Comment by tomkralidis** [comment]
Please post questions to the OWSLib users mailing list. OWSLib's GitHub issues are for **software bugs/enhancements** and related tasks.
