### ISSUE TITLE
WPS execution error

### ISSUE THREAD

**Issue by dpostolovski** [geopython/OWSLib#591]
`execution.getOutput() ` fails on Python 3.7 and 3.6 with error: 

```
File "/Users/xxx/PycharmProjects/xxx/venv/lib/python3.6/site-packages/owslib/wps.py", line 857, in getOutput
    content = content + output_content
TypeError: can't concat str to bytes
```

**Comment by cehbrecht** [comment]
@dpostolovski Thanks for reporting. I have identified some issues with the `bytes` encoding and made a PR #593. I'm not sure if this solves the complete issue. Could you please provide an example?

For testing I was using the Emu WPS:
https://github.com/bird-house/emu

... the `hello`, `chomsky` and `inout` processes.

**Comment by dpostolovski** [comment]
`http://www.soda-is.com/service/wps` with process `get_cams_radiation`

**Comment by cehbrecht** [comment]
@dpostolovski the wps service is maybe blocked by the firewall ... I can't reach it. Did you try with the patch?
https://github.com/geopython/OWSLib/pull/593/files

... or is the source code of the wps available?

**Comment by dpostolovski** [comment]
The server seems to be currently down, so I can't test either. Will let you know when it comes up again.

**Comment by dpostolovski** [comment]
@cehbrecht The service is up again. I confirm that the patch works in my case.

**Comment by cehbrecht** [comment]
@dpostolovski thanks for testing. PR #593 is merged.
