### ISSUE TITLE
test wfs3_ldproxy fails

### ISSUE THREAD

**Issue by cehbrecht** [geopython/OWSLib#625]
This is the test:
https://github.com/geopython/OWSLib/blob/master/tests/test_wfs3_ldproxy.py

The `api()` call does not work:
https://github.com/geopython/OWSLib/blob/5b8fbe866296a9dd98faa30f0b5d7a4fb6036c61/tests/test_wfs3_ldproxy.py#L23

... raises exception:
```
RuntimeError: Did not find service-desc link
```

**Comment by tomkralidis** [comment]
Implemented in #653 and added `pytest.raises` to handle the ldproxy issue until it is fixed on the server.
