### ISSUE TITLE
0.19 release date for #585 fix

### ISSUE THREAD

**Issue by felnne** [geopython/OWSLib#629]
Hi,

Sorry if this isn't the best place to ask this, I'm trying to use OWSlib with an authenticated WMS and have just been bitten by #585. 

I can see this has been fixed as part of the 0.19 release, is this likely to be released soon?

If not is it possible to release a patch release for 0.18 that fixes that problem, only this does exactly what I need!

Thanks

**Comment by cehbrecht** [comment]
@tomkralidis how do you feel about a 0.19 release? Milestone is ready ... we would drop python 2.x.

**Comment by tomkralidis** [comment]
Done.
