### ISSUE TITLE
CSW 3.0

### ISSUE THREAD

**Issue by adborden** [geopython/OWSLib#642]
Support for [CSW 3.0](https://www.opengeospatial.org/standards/cat).

**Comment by adborden** [comment]
Has there been any planning or thought into what the effort is in order to implement this?

**Comment by kalxas** [comment]
no, it has not been discussed so far

**Comment by tomkralidis** [comment]
Note that we are also paving the way for the OGC API standards (see `owslib.ogcapi` for implementation so far).

**Comment by tomkralidis** [comment]
Since implemented against OGC API - Records.
