### ISSUE TITLE
Docs are not up to date

### ISSUE THREAD

**Issue by pathmapper** [geopython/OWSLib#643]
Hi,

according to the changelog WMS 1.3.0 support was added in `0.13.0`:

https://github.com/geopython/OWSLib/blob/master/CHANGES.rst#0130-2016-09-24

but it's not listed as supported: https://geopython.github.io/OWSLib/#standards-support

![grafik](https://user-images.githubusercontent.com/20856381/73140940-b2eaa300-407e-11ea-9673-182cab0268af.png)

**Comment by pathmapper** [comment]
Also the readme of this repo gives more information than the docs page:

e.g. `wms.identification.version` and `wms.identification.abstract` are missing from the docs:

https://github.com/geopython/OWSLib:
![grafik](https://user-images.githubusercontent.com/20856381/73261739-f94e1800-41cc-11ea-9bda-a64071d0cd17.png)

https://geopython.github.io/OWSLib/:
![grafik](https://user-images.githubusercontent.com/20856381/73261651-cdcb2d80-41cc-11ea-948b-0231f397b97b.png)

**Comment by cehbrecht** [comment]
@pathmapper done. Thanks for pointing at this :)

**Comment by pathmapper** [comment]
Thanks @cehbrecht :+1:
