### ISSUE TITLE
Pip package is unable to import owslib.ogcapi

### ISSUE THREAD

**Issue by mattfung** [geopython/OWSLib#666]
OWSLib v0.19.1 package from pip does not seem to have module `owslib.ogcapi`.
However, when I install OWSLib from the latest master source files, I'm able to access this module.

Example from pip package
```
Python 3.7.5 (default, Oct 31 2019, 15:18:51) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import owslib
>>> owslib.__version__
'0.19.0'
>>> from owslib.ogcapi.features import Features
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'owslib.ogcapi'
```

Python 3.7.5 on Win10
Pip version 19.3.1

**Comment by cehbrecht** [comment]
@mattfung I have just tried the pip install with the 0.19.1 package and it works. It looks like you have installed 0.19.0.

**Comment by cehbrecht** [comment]
@mattfung ... I close the ticket.

**Comment by mattfung** [comment]
apologies... long day
