### ISSUE TITLE
WPS WPSExecution.getOutput bug

### ISSUE THREAD

**Issue by huard** [geopython/OWSLib#669]
The code for `getOutput` does not seem to support downloading multiple outputs due to an indentation error.

**Comment by huard** [comment]
Only the first file is downloaded.

**Comment by cehbrecht** [comment]
@huard if you don't already have a fix I will work on this now.

**Comment by huard** [comment]
I don't. The birdy client works around this, so not a blocker for me.

**Comment by cehbrecht** [comment]
well, I guess it is not an indentation issue ... it is old code which just worked for a specific service/purpose. It collects the content of all complex outputs and writes it to a single file ... intentionally. Not what we like to have.

As a quick fix:
* only write a single output
* we can add an optional output identifier to specify the output we want.
* default identifier `output` or None?
