### ISSUE TITLE
Support local files in wps.Output.retrieveData 

### ISSUE THREAD

**Issue by huard** [geopython/OWSLib#680]
When testing WPS processes using the pywps TestClient, output files are stored in /tmp. It would be useful for testing if the owslib client could mock-download those files, as it would simplify writing tests for wps processes.  

We could then do something like:
```
client = client_for(Service(processes=[MyProcess()], cfgfiles=CFG_FILE))
ex = WPSExecution()

resp = client.get(service='wps', request='execute', version='1.0.0', identifier='my-process')
ex.parseResponse(resp.xml)
out = ex.processOutputs[0].retrieveData()
```

**Comment by cehbrecht** [comment]
fixed by PR #681
