### ISSUE TITLE
Release missing for 0.20.0 (and 0.19.2)

### ISSUE THREAD

**Issue by agiudiceandrea** [geopython/OWSLib#696]
The Latest release available on GitHub is 0.19.1 512a273

**Comment by tomkralidis** [comment]
cc @cehbrecht 

Thanks for the report. Release (on GitHub) at https://github.com/geopython/OWSLib/releases/tag/0.20.0.

@cehbrecht why wouldn't this have been propagated to GitHub (without the release text/notes) automatically?  See https://github.com/geopython/pygeoapi/releases for example in pygeoapi (where we do not cut a GitHub release per se)?

**Comment by cehbrecht** [comment]
@tomkralidis can't say what went wrong. Usually if you push a tag it is visible in github releases.
