### ISSUE TITLE
Missing docs for WCS and WFS

### ISSUE THREAD

**Issue by springmeyer** [geopython/OWSLib#70]
I can see that OWSLib supports WCS and WFS but the docs are missing: http://geopython.github.io/OWSLib/#wfs.

Are these services not yet ready to use via OWSLib?

**Comment by neothemachine** [comment]
Please update the docs, it would really help! :)

**Comment by JuergenWeichand** [comment]
WFS docs are now available.
http://geopython.github.io/OWSLib/

**Comment by tomkralidis** [comment]
Thanks again @JuergenWeichand 

@neothemachine echoing @kwilcox, there are some WCS examples in the in unit test which could feed the WCS documentation. Contributions / pull requests are welcome.

**Comment by Zeitsperre** [comment]
@cehbrecht Came here looking for WCS documentation. @huard and I might be able to contribute some of our own examples for WCS calls eventually.
