### ISSUE TITLE
Get elevation data from WMS

### ISSUE THREAD

**Issue by AlexanderJuestel** [geopython/OWSLib#700]
Hello everyone, 

I am loading a WMS service successfully with OWSLib but cannot extract hight information of a digital elevation model. Instead, I only get color values represented by floats. It there a trick to get the height values. Theoretically, the color values should be set with the min and max elevations of the digital elevation model. 

Thanks for the support.
Alex

**Comment by tomkralidis** [comment]
Please post questions to the OWSLib mailing list. OWSLib's GitHub issues are for **software bugs/enhancements** and related tasks.
