### ISSUE TITLE
WMS GetCapabilities: relax the strict check on title and name for Style elements

### ISSUE THREAD

**Issue by giohappy** [geopython/OWSLib#704]
I know that the specification requires both the name and the title to be set for a Style element inside a GetCapabilities response, but many GIS Desktop softwares are a but more easy-going, and will accept the response even if one of them is empty. 

I'm referring to [this line of code](https://github.com/geopython/OWSLib/blob/master/owslib/map/wms130.py#L584) which, in our case, prevents GeoNode to load services that do not expose a Style title.

What if OWSLib was a bit more relaxed on this? Or, if we want to be formally correct, adopt a "strict" option to switch between a strict and relaxed checks.

**Comment by tomkralidis** [comment]
@giohappy thanks for the report.  We can change the code to simply emit a warning instead of the ValueError.  Pull requests welcome (against both 1.1.1 and 1.3.0).

**Comment by giohappy** [comment]
here it is @tomkralidis https://github.com/geopython/OWSLib/pulls

**Comment by tomkralidis** [comment]
Thanks @giohappy !
