### ISSUE TITLE
query or filter ?

### ISSUE THREAD

**Issue by KorkXx** [geopython/OWSLib#710]
https://github.com/geopython/OWSLib/blob/06f8da9c4398d90e8b9efef5e13254706db2458e/owslib/feature/__init__.py#L176

At this line, "query" keyword is used. I would have expected "filter" to be used instead.

On the server I use, with WFS v2.0.0, "query" does not raise error but does not allow filtering, while filter does with identical syntax. 

Bye,
Kork

**Comment by GregMit** [comment]
Hi,

I have the same issue here, WFS 2.0.0 does not allow filtering with `&query=` (it doesn't raise error either)
In 2.0.0 it should be `&filter=`

Bye

Greg
