### ISSUE TITLE
WMS GetCapabilities crash by empty format for DataURL

### ISSUE THREAD

**Issue by vuilleumierc** [geopython/OWSLib#721]
Hi all, 

I have a problem with a WMS GetCapabilities that has an empty format mark-up `<Format/>` (see https://wms.geo.sh.ch/wms?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetCapabilities&ROLE_ID=0&USER_ID=0). The request causes an error (`'NoneType' object has no attribute 'strip'`). 

I am making a PR where I add a test before using the strip function.

**Comment by cehbrecht** [comment]
closed by PR #722
