### ISSUE TITLE
Cartopy wmts KeyError issue : Content metadata for layer "AMSUA_NOAA15_..." already exists

### ISSUE THREAD

**Issue by CTOH-LEGOS** [geopython/OWSLib#768]
#Since a while, I am using the wmts function of cartopy but since last week this function does not works returning this error:

KeyError: 'Content metadata for layer "AMSUA_NOAA15_Brightness_Temp_Channel_10" already exists'

The run code is coming from the cartopy web doc.

below the code:

`
 import matplotlib.pyplot as plt
 import cartopy.crs as ccrs

 def main():
     url = 'https://map1c.vis.earthdata.nasa.gov/wmts-geo/wmts.cgi'
     layer = 'VIIRS_CityLights_2012'

     fig = plt.figure()
     ax = fig.add_subplot(1, 1, 1, projection=ccrs.PlateCarree())
     ax.add_wmts(url, layer)
     ax.set_extent([-15, 25, 35, 60], crs=ccrs.PlateCarree())

     ax.set_title('Suomi NPP Earth at night April/October 2012')
     plt.show()

 if __name__ == '__main__':
     main()
`

The issue come from _buildMetadata method into  WebMapTileService class. The function called gather_layers raise an KeyError if there are duplicated element... But It should be better to add elements if they are not already in the dictionary called "contents"? And just add a warning for duplicate layers.

Below example to fix this issue:
`
 def gather_layers(parent_elem, parent_metadata):
     for index, elem in enumerate(parent_elem.findall(_LAYER_TAG)):
         cm = ContentMetadata( elem, parent=parent_metadata, index=index + 1,parse_remote_metadata=parse_remote_metadata)
         if cm.id:
             if not cm.id in self.contents:
                 self.contents[cm.id] = cm
             else:
                 warnings.war('Content metadata for layer "%s" '
                               'already exists' % cm.id)
         gather_layers(elem, cm)
`

Thank for help.
Fabien Blarel

**Comment by nickdodds** [comment]
Hi, 

Also experiencing the exact same problem as above. I am trying to implement your solution, and was wondering if you had got this working. I did this by doing (you will notice your suggested change to the gather_layer function inside):

'''
from owslib.wmts import WebMapTileService

def custom_buildMetadata(self, parse_remote_metadata=False):
    ''' set up capabilities metadata objects '''

    self.updateSequence = self._capabilities.attrib.get('updateSequence')

    # serviceIdentification metadata
    serviceident = self._capabilities.find(_SERVICE_IDENTIFICATION_TAG)
    self.identification = ServiceIdentification(serviceident)

    # serviceProvider metadata
    serviceprov = self._capabilities.find(_SERVICE_PROVIDER_TAG)
    if serviceprov is not None:
        self.provider = ServiceProvider(serviceprov)

    # serviceOperations metadata
    self.operations = []
    serviceop = self._capabilities.find(_OPERATIONS_METADATA_TAG)
    #  REST only WMTS does not have any Operations
    if serviceop is not None:
        for elem in serviceop[:]:
            self.operations.append(OperationsMetadata(elem))

    # serviceContents metadata: our assumption is that services use
    # a top-level layer as a metadata organizer, nothing more.
    self.contents = {}
    caps = self._capabilities.find(_CONTENTS_TAG)

    def gather_layers(parent_elem, parent_metadata):
        print("Using this gather_layers function")
        for index, elem in enumerate(parent_elem.findall(_LAYER_TAG)):
            cm = ContentMetadata( 
                elem, parent=parent_metadata, index=index + 1,
                parse_remote_metadata=parse_remote_metadata)
            if cm.id:
                if not cm.id in self.contents:
                    self.contents[cm.id] = cm
                else: 
                    warnings.war('Content metadata for layer "%s" ' 'already exists' % cm.id)
            gather_layers(elem, cm)

    self.tilematrixsets = {}
    for elem in caps.findall(_TILE_MATRIX_SET_TAG):
        tms = TileMatrixSet(elem)
        if tms.identifier:
            if tms.identifier in self.tilematrixsets:
                raise KeyError('TileMatrixSet with identifier "%s" '
                                'already exists' % tms.identifier)
            self.tilematrixsets[tms.identifier] = tms

    self.themes = {}
    for elem in self._capabilities.findall(_THEMES_TAG + '/' + _THEME_TAG):
        theme = Theme(elem)
        if theme.identifier:
            if theme.identifier in self.themes:
                raise KeyError('Theme with identifier "%s" already exists'
                                % theme.identifier)
            self.themes[theme.identifier] = theme

    serviceMetadataURL = self._capabilities.find(_SERVICE_METADATA_URL_TAG)
    if serviceMetadataURL is not None:
        self.serviceMetadataURL = serviceMetadataURL.attrib[_HREF_TAG]
    else:
        self.serviceMetadataURL = None

WebMapTileService._buildMetadata = custom_buildMetadata
'''
However now when I am running this, I get a name error from the last step. Have you managed to work around this also?

'''
NameError: name '_SERVICE_IDENTIFICATION_TAG' is not defined
'''

All the best,
Nick

**Comment by nickdodds** [comment]
I tried to implement this in my version, and it then triggered a load more KeyErrors later in the _buildMetadata method. I also had to just change these to warnings.warn (not .war?...). Seems to kick up a fuss but got the end result for me. Thanks for posting this!

**Comment by zfasnacht** [comment]
Any plans to permanently fix this in future updates? Seems it's even breaking active online examples of it's use...

https://scitools.org.uk/cartopy/docs/v0.19/gallery/web_services/wmts_time.html
