### ISSUE TITLE
Submission of Extension Made to Process WCPS queries 

### ISSUE THREAD

**Issue by itsayeshanaeem** [geopython/OWSLib#777]
I am Professor Peter Baumann's student, I worked on implementing WCPS processing via OWSLib and wrote scripts to test my results. 
How would I be able to submit my changes?

**Comment by tomkralidis** [comment]
Hi @itsayeshanaeem your next steps would be to provide a pull request of your updates for code review by OWSLib developers.  See https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/proposing-changes-to-your-work-with-pull-requests for more information on creating pull requests.
