### ISSUE TITLE
getCapabilities with nested Layers

### ISSUE THREAD

**Issue by tomkralidis** [geopython/OWSLib#8]
This getCapabilities File generated by ArcGIS Server 9.3.1 contains nested Layer definitions, where the non-queryable layers don't have a name.

owslib does not allow to get a valid list of layernames out of this getcapabilities response.

there are several issues: 1) the layer-reading should be fully recursive 2) if the layer has got no name defined, there is a problem in the dictionary, as the id is set to the name and thus the layer is not correctly inserted into the dictionnary.

**Comment by Jenselme** [comment]
I will need this feature to parse a getCapabilities from MapServer soon. I found the patch you described above on Github: https://github.com/monoid/owslib/compare/tree It doesn't look too hard to do.

Did you make some progress on that issue since 2012? I should be able to work on it tomorow.

**Comment by tomkralidis** [comment]
No progress and contributions are welcome! Thanks.
