### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by jikuja** [geopython/OWSLib#81]
Some of the changes are possible to do automatically with 2to3: http://pythonhosted.org/distribute/python3.html. I already tried that and manually tested some features. Some parts works but there is still code which doesn't work.

Blockers:
When running tests setup.py loads modules from source directory instead of build directory. Explained and fixed in: http://www.hackzine.org/python-testing-with-pytest-and-2to3-plus-tox-and-travis-ci.html. Anyone familiar enough with (2to3, )test.py and doctests to fix this?

**Comment by Jenselme** [comment]
Hi,

I am interested in python 3 support. I saw that @tbicr did some work some time ago. Any progress? I am willing to help.

**Comment by tomkralidis** [comment]
There has been some smaller PRs in the past months. I suggest following this path.   As well, see related thread on owslib-devel: http://lists.osgeo.org/pipermail/owslib-devel/2015-April/000272.html

**Comment by Jenselme** [comment]
In the last 3.4 branch from @daf there are only two tests failing with python 2.7 and python 3.x and one due to a 404 error. See https://travis-ci.org/Jenselme/OWSLib/builds/61764882 I seems we are close.

**Comment by jorisvandenbossche** [comment]
@tomkralidis now python 3 support has been merged, would it be possible to put a new release on PyPI?

(And I can confirm my application works in python 3 with master!)

**Comment by tigerfoot** [comment]
Without burning lands, it would be really appreciate to get the new release ;-)
If whatever can be done on our side, just tell us.

**Comment by Jenselme** [comment]
:+1:

**Comment by tomkralidis** [comment]
0.9.0 is now [available](https://lists.osgeo.org/pipermail/owslib-users/2015-June/000076.html) -- thanks everyone!

**Comment by jorisvandenbossche** [comment]
Thanks!
