### ISSUE TITLE
Need of additional url request parameters (e.g. for API keys)

### ISSUE THREAD

**Issue by danduk82** [geopython/OWSLib#810]
Some servers require the client to add some additional URL request parameters (for example API keys).

I would like to provide a Pull Request that adds this feature for WMS and WFS services (and harmonize WMTS).

see my PR: https://github.com/geopython/OWSLib/pull/811

Use-case
-------------

**As:** a user
**I want:** use OWSLib as a client for [geoserver OGC server](http://geoserver.org/) with the plugin [authkey](https://docs.geoserver.org/stable/en/user/community/authkey/index.html) which requires the possibility to add `&authkey=<some-uuid>` in the request parameters
**Because:** the server that I must use uses this kind of API keys for access and currently I cannot use OWSLib

**Comment by danduk82** [comment]
@tomkralidis may I ask if you have any opinion on this issue and the respective PR? Just to get a reaction from the maintainer side please.

**Comment by jmckenna** [comment]
This seems like a useful addition to me.

**Comment by tomkralidis** [comment]
In the past, OWSLib has typically delegated extra parameters to be part of the base URL in the constructor.  Example:

```python
from owslib.wms import WebMapService

w = WebMapService('https://example.org/wms?auth_key=123')
```

From a pure WMS standpoint, given the above, the WMS specification functions as expected without needing to manage extra parameters.  Does this approach work for your use case?

**Comment by danduk82** [comment]
@tomkralidis  actually I didn't think that enough and discussing with a colleague also my PR doesn't take into account the fact that the ressource URLs might not lead to the same server.

So indeed, your KISS solution is better. I will close the PR. :+1:
