### ISSUE TITLE
Typos in Usage documentation

### ISSUE THREAD

**Issue by ghobona** [geopython/OWSLib#836]
This issue was discovered during the September 2022 Joint OGC  ISO Code Sprint.

The issue refers to text at https://github.com/geopython/OWSLib/blob/master/docs/en/usage.rst

The text "OGC API - Features 1.0 - Part 1: Core" should be "OGC API - Features - Part 1: Core 1.0"

The text "OGC API - Coverages 1.0 - Part 1: Core" should be "OGC API - Coverages - Part 1: Core 1.0"

The text "OGC API - Processes 1.0 - Part 1: Core" should be "OGC API - Processes - Part 1: Core 1.0"

The text "OGC API - Records 1.0 - Part 1: Core" should be "OGC API - Records - Part 1: Core 1.0"

**Comment by kalxas** [comment]
Thank you @ghobona it has been fixed
