### ISSUE TITLE
'NoneType' object has no attribute 'find' in WebMapService

### ISSUE THREAD

**Issue by davidoesch** [geopython/OWSLib#840]
Hi
OS WIN/LINUX
OWSLib             0.27.2
from owslib.wms import WebMapService
service = WebMapService("https://www.geoportal.ch/services/wms/ktai")

results in 

> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "c:\venv\lib\site-packages\owslib\wms.py", line 50, in WebMapService
>     return wms111.WebMapService_1_1_1(
>   File "c:\venv\lib\site-packages\owslib\map\wms111.py", line 87, in __init__
>     self._buildMetadata(parse_remote_metadata)
>   File "c:\venv\lib\site-packages\owslib\map\wms111.py", line 96, in _buildMetadata
>     self.identification = ServiceIdentification(serviceelem, self.version)
>   File "c:\venv\lib\site-packages\owslib\map\wms111.py", line 358, in __init__
>     self.type = testXMLValue(self._root.find('Name'))
> AttributeError: 'NoneType' object has no attribute 'find'

-> Any hints on that?

**Comment by KTAI-GIS** [comment]
Hi there
The service should work now. Geoinfo reported the fix of the issue. But the services are still not visible under [https://davidoesch.github.io/geoservice_harvester_poc/](url).
Another problem is the visualizer who shows the data somewhere in serbia. (See example KT_ZH)
Do we have to fix something more?
Kind regards

**Comment by davidoesch** [comment]
Thanks!
- I'll look into  KTAI and KTAR services in the next days and will add them. 
- KT_ZH: yes some of the services have still faulty coords ( since they are not correct in the WMS GetCap... will look if I want override it)

**Comment by davidoesch** [comment]
we still have this issue for both WMS 1.3.0 and 1.1.1

service = WebMapService(https://www.geoportal.ch/services/wms/ktai?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetCapabilities)
or
service = WebMapService(https://www.geoportal.ch/services/wms/ktai?SERVICE=WMS&VERSION=1.3.&REQUEST=GetCapabilities)

results in

> 
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "c:\temp\geoservice_harvester_poc\venv\lib\site-packages\owslib\wms.py", line 50, in WebMapService
>     return wms111.WebMapService_1_1_1(
>   File "c:\temp\geoservice_harvester_poc\venv\lib\site-packages\owslib\map\wms111.py", line 87, in __init__
>     self._buildMetadata(parse_remote_metadata)
>   File "c:\temp\geoservice_harvester_poc\venv\lib\site-packages\owslib\map\wms111.py", line 96, in _buildMetadata
>     self.identification = ServiceIdentification(serviceelem, self.version)
>   File "c:\temp\geoservice_harvester_poc\venv\lib\site-packages\owslib\map\wms111.py", line 358, in __init__
>     self.type = testXMLValue(self._root.find('Name'))
> AttributeError: 'NoneType' object has no attribute 'find'

@KTAI-GIS  did the fiy have been already deployed?

**Comment by KTAI-GIS** [comment]
Hi there

I got the following answer from the publisher.

Der Dienst ist erreichbar, capabilities dokument ist ebenfalls lesbar.

Laut dieser Doku sieht der Pfad von Ihnen nicht korrekt aus. https://github.com/geopython/OWSLib

WebMapService('https://www.geoportal.ch/services/wms/ktai?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities', version='1.3.0')

Dieser Aufruf gibt bei uns auch kein Ergebnis.

service = WebMapService(https://www.geoportal.ch/services/wms/ktai?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetCapabilities)

Im Aufruf fehlt die Version des Parameters jedoch.

Best regards

**Comment by davidoesch** [comment]
Bugger me...  I do now parse the version... https://github.com/davidoesch/geoservice_harvester_poc/commit/d5f5c4c35ac231789e030d2c9734af35e6cb6116 and now it works. one of the next run within 24h it will be included
