### ISSUE TITLE
Key Error on WMS

### ISSUE THREAD

**Issue by rhodges** [geopython/OWSLib#845]
I'm getting errors when trying to connect to [NOAA's ERDDAP](https://coastwatch.pfeg.noaa.gov/erddap/wms/index.html) via OWSLib's WebMapService tool:

```
> from owslib.wms import WebMapService
> wms = WebMapService(url='https://coastwatch.pfeg.noaa.gov/erddap/wms/erdMBsstdmday_LonPM180/request', version='1.3.0')
*** KeyError: '{http://www.w3.org/1999/xlink}href'
> wms = WebMapService(url='https://coastwatch.pfeg.noaa.gov/erddap/wms/erdMBsstdmday_LonPM180/request', version='1.1.1')
*** KeyError: '{http://www.w3.org/1999/xlink}href'
```
Python version: 3.8.10
owslib version: 0.27.2
* I also saw this issue on v0.25.x

[GetCapabilities](https://coastwatch.pfeg.noaa.gov/erddap/wms/erdMBsstdmday_LonPM180/request?service=WMS&version=1.3.0&request=GetCapabilities) seems to work as expected and I can view layers pulled from this services using OpenLayers.

Any ideas if the issue is related to my request, the service, or internal to OWSLib?

**Comment by tomkralidis** [comment]
The NOAA ERDDAP WMS defines an incorrect xlink namespace URI:

```xml
xmlns:xlink="https://www.w3.org/1999/xlink"
```

The correct namespace URI should be:

```xml
xmlns:xlink="http://www.w3.org/1999/xlink"
```

The WMS needs to be fixed per above.
