### ISSUE TITLE
Issue with URL encoding of parameters in WMS

### ISSUE THREAD

**Issue by ThomasG77** [geopython/OWSLib#846]
## Why? See below two URLs

Unworking URL. Obtained with Owslib that encode characters `/`,`,` et `:` and it's normal

http://ogc.geo-ide.developpement-durable.gouv.fr/wxs?map=/opt/data/carto/geoide-catalogue/1.4/org_38178/908a2fc2-6752-4eae-952a-142393e657b7.internet.map&service=WMS&version=1.3.0&request=GetMap&layers=N_PERIM_MAET_ZINF_S_R11&styles=&width=800&height=448&crs=EPSG%3A4326&bbox=48.1107%2C1.44041%2C49.2484%2C3.56583&format=image%2Fpng&transparent=FALSE&bgcolor=0xFFFFFF&exceptions=XML

vs

Working URL

http://ogc.geo-ide.developpement-durable.gouv.fr/wxs?map=/opt/data/carto/geoide-catalogue/1.4/org_38178/908a2fc2-6752-4eae-952a-142393e657b7.internet.map&service=WMS&version=1.3.0&request=GetMap&layers=N_PERIM_MAET_ZINF_S_R11&styles=&width=800&height=448&crs=EPSG:4326&bbox=48.1107,1.44041,49.2484,3.56583&format=image/png&transparent=FALSE&bgcolor=0xFFFFFF&exceptions=XML

The issue seems to be on the server side of the service I consume that does not decode the encoded parameters.

## Code to reproduce how I got the following URL

```python
from owslib.wms import WebMapService

wms = WebMapService('https://ogc.geo-ide.developpement-durable.gouv.fr/wxs?map=/opt/data/carto/geoide-catalogue/1.4/org_38178/908a2fc2-6752-4eae-952a-142393e657b7.internet.map', version='1.3.0')

response = wms.getmap(layers=['N_PERIM_MAET_ZINF_S_R11',],
    bbox=(1.44041, 48.1107, 3.56583, 49.2484),
    format='image/png',
    size=(800, 428),
    srs='EPSG:4326',
)
with open(f"N_PERIM_MAET_ZINF_S_R11.png", 'wb') as out:
    out.write(response.read())
```

## Possible approach

To solve the issue, I want to use the safe option of https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urlencode

`getmap` method would get a new `safe` option, empty by default (like the normal `urlencode` behavior) but could be changed at https://github.com/geopython/OWSLib/blob/master/owslib/map/wms111.py#L258 and https://github.com/geopython/OWSLib/blob/master/owslib/map/wms111.py#L258 and https://github.com/geopython/OWSLib/blob/master/owslib/map/wms130.py#L304
where

```
data = urlencode(request)
```

would be replaced by
```
data = urlencode(request,safe)
```

So, it can help solve the issue when you do not control the server encode/decode behavior while not breaking anything. I would be able to provide to the new `safe` option the value `:/,` in my case (already tested with hardcoded value while debugging) .

PS: I can do a PR but need to confirm the logic could be fine on owslib project. Moreover, I've only look at the WMS code part but this could be applied maybe to other types of webservices with the same issue.

**Comment by sbrunner** [comment]
When you create the WebMapService the map path should be encoded:
```python
wms = WebMapService('https://ogc.geo-ide.developpement-durable.gouv.fr/wxs?map=%2Fopt%2Fdata%2Fcarto%2Fgeoide-catalogue%2F1.4%2Forg_38178%2F908a2fc2-6752-4eae-952a-142393e657b7.internet.map', version='1.3.0')
```
And you should be directly in https because the http to https redirect will break the URL...

**Comment by sbrunner** [comment]
With the version `0.25.0` it's working...

**Comment by sbrunner** [comment]
I think that a better solution is to have an option to skip this kind of code...
https://github.com/geopython/OWSLib/blob/018c7f83fb042a6390d65aaa683110743609f3e3/owslib/map/wms130.py#L283-L285
and use directly self.url :-)

**Comment by ThomasG77** [comment]
Using 0.27.2 and not working. I've tested 0.25.0 and working...

**Comment by yagossc** [comment]
Is this still a problem?

I'm using `__version__ = '0.31.0'`

I create a wfs instance passing a URL that uses HTTPS:
``` python
WebFeatureService("https://domain/path/etc", version="2.0.0")
```

However, when I call the method `getfeature(typename="blabla", ...)` the request is made using HTTP.

The server I'm trying to reach only allows https requests and returns redirects otherwise (i.e., `302 Found`).

Is there a workaround somewhere that I couldn't find? This is the only issue I found mentioning this specific case.
