### ISSUE TITLE
Send files as ComplexData to WPS

### ISSUE THREAD

**Issue by sehHeiden** [geopython/OWSLib#852]
I am trying an [PyWPS example](https://github.com/geopython/pywps-flask/blob/master/processes/buffer.py) and want to send a GML Layer as ComplexData to get the buffer.
The question, I have, is: How do I send the vector file to the WPS with ows?

I could not find any description in the documentation!

**Comment by huard** [comment]
We use a high-level WPS client to ease the process of sending files as WPS inputs, see https://github.com/bird-house/birdy

You'll be able to find the embedding logic in the code, which uses owslib.
