### ISSUE TITLE
Missing change logs for `0.28.x` versions

### ISSUE THREAD

**Issue by fmigneault** [geopython/OWSLib#867]
https://github.com/geopython/OWSLib/blob/master/CHANGES.rst does not have the relevant changes from https://github.com/geopython/OWSLib/releases/tag/0.28.0 and https://github.com/geopython/OWSLib/releases/tag/0.28.1

Given that a security advisory (example: https://github.com/crim-ca/weaver/security/dependabot/3) for `owslib<0.28.1` was created, it would be important to have the details highlighted for maintainers that need to understand what other changes are implied in new versions.

**Comment by tomkralidis** [comment]
FYI see https://github.com/geopython/OWSLib/pull/870, which removes `CHANGES.rst` as part of a larger housekeeping update.
