### ISSUE TITLE
AttributeError: module 'logging' has no attribute 'isEnabledFor'

### ISSUE THREAD

**Issue by disbr007** [geopython/OWSLib#871]
Just started seeing this error pop yesterday from my project that uses `owslib`. I'm not version pinned so assuming this is related to [release from yesterday](https://github.com/geopython/OWSLib/releases/tag/0.29.0).

```
 r = wcs.getCoverage(

  File "/usr/local/lib/python3.8/dist-packages/owslib/coverage/wcs201.py", line 156, in getCoverage

    if log.isEnabledFor(logging.DEBUG):

AttributeError: module 'logging' has no attribute 'isEnabledFor'
```

**Comment by alesolla** [comment]
Hi! Is there any update on when this will be updated in the pypi released version?
