### ISSUE TITLE
broken WPS since 0.29.0 

### ISSUE THREAD

**Issue by fmigneault** [geopython/OWSLib#893]
WPS is broken since https://github.com/geopython/OWSLib/commit/e8dd55fb1d349dde0e2c7881fa9103681708201c, (ie: https://github.com/geopython/OWSLib/releases/tag/0.29.0) 

This is because of changes like this one: 
https://github.com/geopython/OWSLib/blob/e8dd55fb1d349dde0e2c7881fa9103681708201c/owslib/wps.py#L1614

https://github.com/geopython/OWSLib/commit/e8dd55fb1d349dde0e2c7881fa9103681708201c#diff-9549cfa74c19d24dedb1e46b21f43c1a0b0986b018503074db64e219f08423deR1614

that replaced the `dump` function with `prefix` parameter, which `logging` functions don't have.

blocks https://github.com/crim-ca/weaver/pull/577
error: https://github.com/crim-ca/weaver/actions/runs/6535582805/job/17745369444?pr=577

**Comment by tomkralidis** [comment]
PR in #894.  Can you test?
