### ISSUE TITLE
dublin core as an import option

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/OWSLib#909]
currently parsing a dublin core record is implemented as part of the csw parsing

https://github.com/geopython/OWSLib/blob/46d89334c34a418f5a57b623cd0c07f3bdbf775a/owslib/csw.py#L616

would it make sense to delegate that to a dedicated dublin core parser

so we can also use owslib to parse dublin-core.xml files

added are some dublin core records exported from zenodo

[zenodo_xml.zip](https://github.com/geopython/OWSLib/files/14521906/zenodo_xml.zip)

**Comment by tomkralidis** [comment]
Good idea @pvgenuchten.  In theory, CSW Record is Dublin Core + extra elements like `ows:BoundingBox` and `ows:WGS84BoundingBox`.

Perhaps we can move the pure DC model to `owslib.dublincore.DublinCore` and have `owslib.csw.CswRecord` subclass accordingly?
