### ISSUE TITLE
timeout isn't being used for WebCoverageService 

### ISSUE THREAD

**Issue by mikedig** [geopython/OWSLib#915]
Trying to change the timeout from the default of 30 seconds, but it doesn't seem to apply. 

`WebCoverageService(uri, version=WCS_VERSION, timeout=60)`

this ends up calling WCSBase.\_\_new__ which has the timeout value as 60 correctly, however when obj.\_\_init__ is called (https://github.com/geopython/OWSLib/blob/master/owslib/coverage/wcsBase.py#L49) it doesn't pass the timeout value. In the debugger I see wcs100.py's \_\_init__ have the default timeout of 30 seconds: https://github.com/geopython/OWSLib/blob/master/owslib/coverage/wcs100.py#L40

Is this intended behavior?

**Comment by tomkralidis** [comment]
Fixed by #914
